-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity DNN_DNN_Pipeline_VITIS_LOOP_60_1_VITIS_LOOP_61_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv1_output_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    conv1_output_ce0 : OUT STD_LOGIC;
    conv1_output_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv1_output_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    conv1_output_ce1 : OUT STD_LOGIC;
    conv1_output_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv1_output_address2 : OUT STD_LOGIC_VECTOR (5 downto 0);
    conv1_output_ce2 : OUT STD_LOGIC;
    conv1_output_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv1_output_address3 : OUT STD_LOGIC_VECTOR (5 downto 0);
    conv1_output_ce3 : OUT STD_LOGIC;
    conv1_output_q3 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv1_output_address4 : OUT STD_LOGIC_VECTOR (5 downto 0);
    conv1_output_ce4 : OUT STD_LOGIC;
    conv1_output_q4 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv1_output_address5 : OUT STD_LOGIC_VECTOR (5 downto 0);
    conv1_output_ce5 : OUT STD_LOGIC;
    conv1_output_q5 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv1_output_address6 : OUT STD_LOGIC_VECTOR (5 downto 0);
    conv1_output_ce6 : OUT STD_LOGIC;
    conv1_output_q6 : IN STD_LOGIC_VECTOR (31 downto 0);
    pool1_output_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    pool1_output_ce0 : OUT STD_LOGIC;
    pool1_output_we0 : OUT STD_LOGIC;
    pool1_output_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1544_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1544_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1544_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1544_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1544_p_ce : OUT STD_LOGIC;
    grp_fu_1548_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1548_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1548_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1548_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1548_p_ce : OUT STD_LOGIC;
    grp_fu_1552_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1552_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1552_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1552_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1552_p_ce : OUT STD_LOGIC );
end;


architecture behav of DNN_DNN_Pipeline_VITIS_LOOP_60_1_VITIS_LOOP_61_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln60_fu_209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln60_fu_241_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln60_reg_706 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln60_reg_706_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_43_cast_fu_261_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_43_cast_reg_711 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_43_cast_reg_711_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln65_fu_302_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln65_reg_721 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln65_reg_721_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln65_reg_721_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln65_reg_721_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln65_fu_313_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln65_reg_731 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln65_reg_731_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_332_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_16_reg_741 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_16_reg_741_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_16_reg_741_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_16_reg_741_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_16_reg_741_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_16_reg_741_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_reg_751 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_17_reg_751_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_17_reg_751_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_17_reg_751_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_17_reg_751_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_17_reg_751_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_17_reg_751_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_reg_756 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_reg_756_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_reg_756_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_reg_756_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_reg_756_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_reg_756_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_reg_756_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln65_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_771 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_1_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_1_reg_776 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_2_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_2_reg_781 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_3_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_3_reg_786 : STD_LOGIC_VECTOR (0 downto 0);
    signal conv1_output_load_2_reg_791 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv1_output_load_2_reg_791_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv1_output_load_4_reg_797 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv1_output_load_4_reg_797_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv1_output_load_4_reg_797_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal conv1_output_load_4_reg_797_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_1_fu_480_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln65_1_reg_803 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln65_1_reg_803_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln65_4_fu_525_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_4_reg_818 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_5_fu_531_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_5_reg_823 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_6_fu_537_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_6_reg_828 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_7_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_7_reg_833 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln65_1_fu_569_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln65_1_reg_838 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln65_1_reg_838_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln65_8_fu_615_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_8_reg_853 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_9_fu_621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_9_reg_858 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_10_fu_627_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_10_reg_863 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_11_fu_633_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_11_reg_868 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln62_1_fu_297_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln65_fu_308_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln65_2_fu_327_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln65_3_fu_340_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln65_5_fu_485_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln65_6_fu_575_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln65_7_fu_665_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln70_fu_676_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_64 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln61_fu_365_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_fu_68 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln60_1_fu_249_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten24_fu_72 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten24_load : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln60_1_fu_215_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_233_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln60_fu_227_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln62_fu_257_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln60_fu_269_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln62_fu_287_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln62_fu_291_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_14_fu_275_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_61_fu_283_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_319_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal bitcast_ln65_fu_386_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln65_1_fu_404_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_390_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln65_fu_400_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_4_fu_408_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln65_1_fu_418_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln65_1_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln65_2_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_1_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln65_1_fu_446_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln65_fu_469_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln65_4_fu_476_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal bitcast_ln65_2_fu_490_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln65_3_fu_507_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_493_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln65_2_fu_503_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_7_fu_511_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln65_3_fu_521_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln65_3_fu_549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln65_4_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_2_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_3_fu_563_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln65_4_fu_580_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln65_5_fu_597_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_583_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln65_4_fu_593_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_s_fu_601_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln65_5_fu_611_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln65_5_fu_639_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln65_6_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_4_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_5_fu_653_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln65_2_fu_659_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_19_fu_670_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component DNN_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component DNN_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component DNN_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    i_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln60_fu_209_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_68 <= select_ln60_1_fu_249_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_68 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten24_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln60_fu_209_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten24_fu_72 <= add_ln60_1_fu_215_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten24_fu_72 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln60_fu_209_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_64 <= add_ln61_fu_365_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_64 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln65_1_reg_803 <= add_ln65_1_fu_480_p2;
                add_ln65_1_reg_803_pp0_iter3_reg <= add_ln65_1_reg_803;
                add_ln65_reg_721_pp0_iter2_reg <= add_ln65_reg_721_pp0_iter1_reg;
                add_ln65_reg_721_pp0_iter3_reg <= add_ln65_reg_721_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                conv1_output_load_2_reg_791_pp0_iter2_reg <= conv1_output_load_2_reg_791;
                conv1_output_load_4_reg_797_pp0_iter2_reg <= conv1_output_load_4_reg_797;
                conv1_output_load_4_reg_797_pp0_iter3_reg <= conv1_output_load_4_reg_797_pp0_iter2_reg;
                conv1_output_load_4_reg_797_pp0_iter4_reg <= conv1_output_load_4_reg_797_pp0_iter3_reg;
                icmp_ln65_10_reg_863 <= icmp_ln65_10_fu_627_p2;
                icmp_ln65_11_reg_868 <= icmp_ln65_11_fu_633_p2;
                icmp_ln65_4_reg_818 <= icmp_ln65_4_fu_525_p2;
                icmp_ln65_5_reg_823 <= icmp_ln65_5_fu_531_p2;
                icmp_ln65_6_reg_828 <= icmp_ln65_6_fu_537_p2;
                icmp_ln65_7_reg_833 <= icmp_ln65_7_fu_543_p2;
                icmp_ln65_8_reg_853 <= icmp_ln65_8_fu_615_p2;
                icmp_ln65_9_reg_858 <= icmp_ln65_9_fu_621_p2;
                select_ln65_1_reg_838 <= select_ln65_1_fu_569_p3;
                select_ln65_1_reg_838_pp0_iter5_reg <= select_ln65_1_reg_838;
                    tmp_16_reg_741_pp0_iter2_reg(2 downto 1) <= tmp_16_reg_741_pp0_iter1_reg(2 downto 1);    tmp_16_reg_741_pp0_iter2_reg(5 downto 4) <= tmp_16_reg_741_pp0_iter1_reg(5 downto 4);
                    tmp_16_reg_741_pp0_iter3_reg(2 downto 1) <= tmp_16_reg_741_pp0_iter2_reg(2 downto 1);    tmp_16_reg_741_pp0_iter3_reg(5 downto 4) <= tmp_16_reg_741_pp0_iter2_reg(5 downto 4);
                    tmp_16_reg_741_pp0_iter4_reg(2 downto 1) <= tmp_16_reg_741_pp0_iter3_reg(2 downto 1);    tmp_16_reg_741_pp0_iter4_reg(5 downto 4) <= tmp_16_reg_741_pp0_iter3_reg(5 downto 4);
                    tmp_16_reg_741_pp0_iter5_reg(2 downto 1) <= tmp_16_reg_741_pp0_iter4_reg(2 downto 1);    tmp_16_reg_741_pp0_iter5_reg(5 downto 4) <= tmp_16_reg_741_pp0_iter4_reg(5 downto 4);
                tmp_17_reg_751_pp0_iter2_reg <= tmp_17_reg_751_pp0_iter1_reg;
                tmp_17_reg_751_pp0_iter3_reg <= tmp_17_reg_751_pp0_iter2_reg;
                tmp_17_reg_751_pp0_iter4_reg <= tmp_17_reg_751_pp0_iter3_reg;
                tmp_17_reg_751_pp0_iter5_reg <= tmp_17_reg_751_pp0_iter4_reg;
                tmp_17_reg_751_pp0_iter6_reg <= tmp_17_reg_751_pp0_iter5_reg;
                tmp_18_reg_756_pp0_iter2_reg <= tmp_18_reg_756_pp0_iter1_reg;
                tmp_18_reg_756_pp0_iter3_reg <= tmp_18_reg_756_pp0_iter2_reg;
                tmp_18_reg_756_pp0_iter4_reg <= tmp_18_reg_756_pp0_iter3_reg;
                tmp_18_reg_756_pp0_iter5_reg <= tmp_18_reg_756_pp0_iter4_reg;
                tmp_18_reg_756_pp0_iter6_reg <= tmp_18_reg_756_pp0_iter5_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln60_fu_209_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln65_reg_721 <= add_ln65_fu_302_p2;
                    or_ln65_reg_731(2 downto 1) <= or_ln65_fu_313_p2(2 downto 1);
                select_ln60_reg_706 <= select_ln60_fu_241_p3;
                    tmp_16_reg_741(2 downto 1) <= tmp_16_fu_332_p3(2 downto 1);    tmp_16_reg_741(5 downto 4) <= tmp_16_fu_332_p3(5 downto 4);
                tmp_17_reg_751 <= select_ln60_fu_241_p3(2 downto 1);
                tmp_18_reg_756 <= select_ln60_1_fu_249_p3(2 downto 1);
                    tmp_43_cast_reg_711(5 downto 3) <= tmp_43_cast_fu_261_p3(5 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln65_reg_721_pp0_iter1_reg <= add_ln65_reg_721;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln65_1_reg_776 <= icmp_ln65_1_fu_428_p2;
                icmp_ln65_2_reg_781 <= icmp_ln65_2_fu_434_p2;
                icmp_ln65_3_reg_786 <= icmp_ln65_3_fu_440_p2;
                icmp_ln65_reg_771 <= icmp_ln65_fu_422_p2;
                    or_ln65_reg_731_pp0_iter1_reg(2 downto 1) <= or_ln65_reg_731(2 downto 1);
                select_ln60_reg_706_pp0_iter1_reg <= select_ln60_reg_706;
                    tmp_16_reg_741_pp0_iter1_reg(2 downto 1) <= tmp_16_reg_741(2 downto 1);    tmp_16_reg_741_pp0_iter1_reg(5 downto 4) <= tmp_16_reg_741(5 downto 4);
                tmp_17_reg_751_pp0_iter1_reg <= tmp_17_reg_751;
                tmp_18_reg_756_pp0_iter1_reg <= tmp_18_reg_756;
                    tmp_43_cast_reg_711_pp0_iter1_reg(5 downto 3) <= tmp_43_cast_reg_711(5 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                conv1_output_load_2_reg_791 <= conv1_output_q4;
                conv1_output_load_4_reg_797 <= conv1_output_q3;
            end if;
        end if;
    end process;
    tmp_43_cast_reg_711(2 downto 0) <= "000";
    tmp_43_cast_reg_711_pp0_iter1_reg(2 downto 0) <= "000";
    or_ln65_reg_731(0) <= '1';
    or_ln65_reg_731_pp0_iter1_reg(0) <= '1';
    tmp_16_reg_741(0) <= '1';
    tmp_16_reg_741(3) <= '1';
    tmp_16_reg_741_pp0_iter1_reg(0) <= '1';
    tmp_16_reg_741_pp0_iter1_reg(3) <= '1';
    tmp_16_reg_741_pp0_iter2_reg(0) <= '1';
    tmp_16_reg_741_pp0_iter2_reg(3) <= '1';
    tmp_16_reg_741_pp0_iter3_reg(0) <= '1';
    tmp_16_reg_741_pp0_iter3_reg(3) <= '1';
    tmp_16_reg_741_pp0_iter4_reg(0) <= '1';
    tmp_16_reg_741_pp0_iter4_reg(3) <= '1';
    tmp_16_reg_741_pp0_iter5_reg(0) <= '1';
    tmp_16_reg_741_pp0_iter5_reg(3) <= '1';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln60_1_fu_215_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten24_load) + unsigned(ap_const_lv5_1));
    add_ln60_fu_227_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv4_2));
    add_ln61_fu_365_p2 <= std_logic_vector(unsigned(select_ln60_fu_241_p3) + unsigned(ap_const_lv4_2));
    add_ln62_fu_291_p2 <= std_logic_vector(unsigned(tmp_43_cast_fu_261_p3) + unsigned(zext_ln62_fu_287_p1));
    add_ln65_1_fu_480_p2 <= std_logic_vector(unsigned(tmp_43_cast_reg_711_pp0_iter1_reg) + unsigned(zext_ln65_4_fu_476_p1));
    add_ln65_fu_302_p2 <= std_logic_vector(unsigned(tmp_14_fu_275_p3) + unsigned(zext_ln62_fu_287_p1));
    and_ln65_1_fu_463_p2 <= (grp_fu_1544_p_dout0 and and_ln65_fu_457_p2);
    and_ln65_2_fu_557_p2 <= (or_ln65_4_fu_553_p2 and or_ln65_3_fu_549_p2);
    and_ln65_3_fu_563_p2 <= (grp_fu_1548_p_dout0 and and_ln65_2_fu_557_p2);
    and_ln65_4_fu_647_p2 <= (or_ln65_6_fu_643_p2 and or_ln65_5_fu_639_p2);
    and_ln65_5_fu_653_p2 <= (grp_fu_1552_p_dout0 and and_ln65_4_fu_647_p2);
    and_ln65_fu_457_p2 <= (or_ln65_2_fu_453_p2 and or_ln65_1_fu_449_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln60_fu_209_p2)
    begin
        if (((icmp_ln60_fu_209_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_68)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_68;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten24_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten24_fu_72)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten24_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten24_load <= indvar_flatten24_fu_72;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_64, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_64;
        end if; 
    end process;

    bitcast_ln65_1_fu_404_p1 <= conv1_output_q6;
    bitcast_ln65_2_fu_490_p1 <= conv1_output_load_2_reg_791_pp0_iter2_reg;
    bitcast_ln65_3_fu_507_p1 <= conv1_output_q2;
    bitcast_ln65_4_fu_580_p1 <= conv1_output_load_4_reg_797_pp0_iter4_reg;
    bitcast_ln65_5_fu_597_p1 <= conv1_output_q1;
    bitcast_ln65_fu_386_p1 <= conv1_output_q5;
    conv1_output_address0 <= zext_ln65_7_fu_665_p1(6 - 1 downto 0);
    conv1_output_address1 <= zext_ln65_6_fu_575_p1(6 - 1 downto 0);
    conv1_output_address2 <= zext_ln65_5_fu_485_p1(6 - 1 downto 0);
    conv1_output_address3 <= zext_ln65_3_fu_340_p1(6 - 1 downto 0);
    conv1_output_address4 <= zext_ln65_fu_308_p1(6 - 1 downto 0);
    conv1_output_address5 <= zext_ln65_2_fu_327_p1(6 - 1 downto 0);
    conv1_output_address6 <= zext_ln62_1_fu_297_p1(6 - 1 downto 0);

    conv1_output_ce0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            conv1_output_ce0 <= ap_const_logic_1;
        else 
            conv1_output_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    conv1_output_ce1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            conv1_output_ce1 <= ap_const_logic_1;
        else 
            conv1_output_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    conv1_output_ce2_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            conv1_output_ce2 <= ap_const_logic_1;
        else 
            conv1_output_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    conv1_output_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv1_output_ce3 <= ap_const_logic_1;
        else 
            conv1_output_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    conv1_output_ce4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv1_output_ce4 <= ap_const_logic_1;
        else 
            conv1_output_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    conv1_output_ce5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv1_output_ce5 <= ap_const_logic_1;
        else 
            conv1_output_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    conv1_output_ce6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv1_output_ce6 <= ap_const_logic_1;
        else 
            conv1_output_ce6 <= ap_const_logic_0;
        end if; 
    end process;

    empty_61_fu_283_p1 <= select_ln60_fu_241_p3(3 - 1 downto 0);
    grp_fu_1544_p_ce <= ap_const_logic_1;
    grp_fu_1544_p_din0 <= conv1_output_q5;
    grp_fu_1544_p_din1 <= conv1_output_q6;
    grp_fu_1544_p_opcode <= ap_const_lv5_2;
    grp_fu_1548_p_ce <= ap_const_logic_1;
    grp_fu_1548_p_din0 <= conv1_output_load_2_reg_791_pp0_iter2_reg;
    grp_fu_1548_p_din1 <= conv1_output_q2;
    grp_fu_1548_p_opcode <= ap_const_lv5_2;
    grp_fu_1552_p_ce <= ap_const_logic_1;
    grp_fu_1552_p_din0 <= conv1_output_load_4_reg_797_pp0_iter4_reg;
    grp_fu_1552_p_din1 <= conv1_output_q1;
    grp_fu_1552_p_opcode <= ap_const_lv5_2;
    icmp_ln60_fu_209_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten24_load = ap_const_lv5_10) else "0";
    icmp_ln65_10_fu_627_p2 <= "0" when (tmp_s_fu_601_p4 = ap_const_lv8_FF) else "1";
    icmp_ln65_11_fu_633_p2 <= "1" when (trunc_ln65_5_fu_611_p1 = ap_const_lv23_0) else "0";
    icmp_ln65_1_fu_428_p2 <= "1" when (trunc_ln65_fu_400_p1 = ap_const_lv23_0) else "0";
    icmp_ln65_2_fu_434_p2 <= "0" when (tmp_4_fu_408_p4 = ap_const_lv8_FF) else "1";
    icmp_ln65_3_fu_440_p2 <= "1" when (trunc_ln65_1_fu_418_p1 = ap_const_lv23_0) else "0";
    icmp_ln65_4_fu_525_p2 <= "0" when (tmp_6_fu_493_p4 = ap_const_lv8_FF) else "1";
    icmp_ln65_5_fu_531_p2 <= "1" when (trunc_ln65_2_fu_503_p1 = ap_const_lv23_0) else "0";
    icmp_ln65_6_fu_537_p2 <= "0" when (tmp_7_fu_511_p4 = ap_const_lv8_FF) else "1";
    icmp_ln65_7_fu_543_p2 <= "1" when (trunc_ln65_3_fu_521_p1 = ap_const_lv23_0) else "0";
    icmp_ln65_8_fu_615_p2 <= "0" when (tmp_9_fu_583_p4 = ap_const_lv8_FF) else "1";
    icmp_ln65_9_fu_621_p2 <= "1" when (trunc_ln65_4_fu_593_p1 = ap_const_lv23_0) else "0";
    icmp_ln65_fu_422_p2 <= "0" when (tmp_3_fu_390_p4 = ap_const_lv8_FF) else "1";
    or_ln60_fu_269_p2 <= (trunc_ln62_fu_257_p1 or ap_const_lv3_1);
    or_ln65_1_fu_449_p2 <= (icmp_ln65_reg_771 or icmp_ln65_1_reg_776);
    or_ln65_2_fu_453_p2 <= (icmp_ln65_3_reg_786 or icmp_ln65_2_reg_781);
    or_ln65_3_fu_549_p2 <= (icmp_ln65_5_reg_823 or icmp_ln65_4_reg_818);
    or_ln65_4_fu_553_p2 <= (icmp_ln65_7_reg_833 or icmp_ln65_6_reg_828);
    or_ln65_5_fu_639_p2 <= (icmp_ln65_9_reg_858 or icmp_ln65_8_reg_853);
    or_ln65_6_fu_643_p2 <= (icmp_ln65_11_reg_868 or icmp_ln65_10_reg_863);
    or_ln65_fu_313_p2 <= (empty_61_fu_283_p1 or ap_const_lv3_1);
    pool1_output_address0 <= zext_ln70_fu_676_p1(4 - 1 downto 0);

    pool1_output_ce0_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            pool1_output_ce0 <= ap_const_logic_1;
        else 
            pool1_output_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pool1_output_d0 <= conv1_output_q0;

    pool1_output_we0_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            pool1_output_we0 <= ap_const_logic_1;
        else 
            pool1_output_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln60_1_fu_249_p3 <= 
        add_ln60_fu_227_p2 when (tmp_fu_233_p3(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln60_fu_241_p3 <= 
        ap_const_lv4_0 when (tmp_fu_233_p3(0) = '1') else 
        ap_sig_allocacmp_j_load;
    select_ln65_1_fu_569_p3 <= 
        add_ln65_reg_721_pp0_iter3_reg when (and_ln65_3_fu_563_p2(0) = '1') else 
        add_ln65_1_reg_803_pp0_iter3_reg;
    select_ln65_2_fu_659_p3 <= 
        tmp_16_reg_741_pp0_iter5_reg when (and_ln65_5_fu_653_p2(0) = '1') else 
        select_ln65_1_reg_838_pp0_iter5_reg;
    select_ln65_fu_469_p3 <= 
        zext_ln65_1_fu_446_p1 when (and_ln65_1_fu_463_p2(0) = '1') else 
        select_ln60_reg_706_pp0_iter1_reg;
    tmp_14_fu_275_p3 <= (or_ln60_fu_269_p2 & ap_const_lv3_0);
    tmp_15_fu_319_p3 <= (select_ln60_1_fu_249_p3 & or_ln65_fu_313_p2);
    tmp_16_fu_332_p3 <= (or_ln60_fu_269_p2 & or_ln65_fu_313_p2);
    tmp_19_fu_670_p3 <= (tmp_18_reg_756_pp0_iter6_reg & tmp_17_reg_751_pp0_iter6_reg);
    tmp_3_fu_390_p4 <= bitcast_ln65_fu_386_p1(30 downto 23);
    tmp_43_cast_fu_261_p3 <= (trunc_ln62_fu_257_p1 & ap_const_lv3_0);
    tmp_4_fu_408_p4 <= bitcast_ln65_1_fu_404_p1(30 downto 23);
    tmp_6_fu_493_p4 <= bitcast_ln65_2_fu_490_p1(30 downto 23);
    tmp_7_fu_511_p4 <= bitcast_ln65_3_fu_507_p1(30 downto 23);
    tmp_9_fu_583_p4 <= bitcast_ln65_4_fu_580_p1(30 downto 23);
    tmp_fu_233_p3 <= ap_sig_allocacmp_j_load(3 downto 3);
    tmp_s_fu_601_p4 <= bitcast_ln65_5_fu_597_p1(30 downto 23);
    trunc_ln62_fu_257_p1 <= select_ln60_1_fu_249_p3(3 - 1 downto 0);
    trunc_ln65_1_fu_418_p1 <= bitcast_ln65_1_fu_404_p1(23 - 1 downto 0);
    trunc_ln65_2_fu_503_p1 <= bitcast_ln65_2_fu_490_p1(23 - 1 downto 0);
    trunc_ln65_3_fu_521_p1 <= bitcast_ln65_3_fu_507_p1(23 - 1 downto 0);
    trunc_ln65_4_fu_593_p1 <= bitcast_ln65_4_fu_580_p1(23 - 1 downto 0);
    trunc_ln65_5_fu_611_p1 <= bitcast_ln65_5_fu_597_p1(23 - 1 downto 0);
    trunc_ln65_fu_400_p1 <= bitcast_ln65_fu_386_p1(23 - 1 downto 0);
    zext_ln62_1_fu_297_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln62_fu_291_p2),64));
    zext_ln62_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln60_fu_241_p3),6));
    zext_ln65_1_fu_446_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln65_reg_731_pp0_iter1_reg),4));
    zext_ln65_2_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_319_p3),64));
    zext_ln65_3_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_16_fu_332_p3),64));
    zext_ln65_4_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln65_fu_469_p3),6));
    zext_ln65_5_fu_485_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln65_1_fu_480_p2),64));
    zext_ln65_6_fu_575_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln65_1_fu_569_p3),64));
    zext_ln65_7_fu_665_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln65_2_fu_659_p3),64));
    zext_ln65_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln65_fu_302_p2),64));
    zext_ln70_fu_676_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_fu_670_p3),64));
end behav;
