-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity DNN_DNN_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    temp_input_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    temp_input_ce0 : OUT STD_LOGIC;
    temp_input_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_input_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    temp_input_ce1 : OUT STD_LOGIC;
    temp_input_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_input_address2 : OUT STD_LOGIC_VECTOR (6 downto 0);
    temp_input_ce2 : OUT STD_LOGIC;
    temp_input_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_input_address3 : OUT STD_LOGIC_VECTOR (6 downto 0);
    temp_input_ce3 : OUT STD_LOGIC;
    temp_input_q3 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_input_address4 : OUT STD_LOGIC_VECTOR (6 downto 0);
    temp_input_ce4 : OUT STD_LOGIC;
    temp_input_q4 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_input_address5 : OUT STD_LOGIC_VECTOR (6 downto 0);
    temp_input_ce5 : OUT STD_LOGIC;
    temp_input_q5 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_input_address6 : OUT STD_LOGIC_VECTOR (6 downto 0);
    temp_input_ce6 : OUT STD_LOGIC;
    temp_input_q6 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_input_address7 : OUT STD_LOGIC_VECTOR (6 downto 0);
    temp_input_ce7 : OUT STD_LOGIC;
    temp_input_q7 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_input_address8 : OUT STD_LOGIC_VECTOR (6 downto 0);
    temp_input_ce8 : OUT STD_LOGIC;
    temp_input_q8 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv1_output_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    conv1_output_ce0 : OUT STD_LOGIC;
    conv1_output_we0 : OUT STD_LOGIC;
    conv1_output_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1472_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1472_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1472_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1472_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1472_p_ce : OUT STD_LOGIC;
    grp_fu_1476_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1476_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1476_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1476_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1476_p_ce : OUT STD_LOGIC;
    grp_fu_1480_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1480_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1480_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1480_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1480_p_ce : OUT STD_LOGIC;
    grp_fu_1484_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1484_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1484_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1484_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1484_p_ce : OUT STD_LOGIC;
    grp_fu_1488_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1488_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1488_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1488_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1488_p_ce : OUT STD_LOGIC;
    grp_fu_1492_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1492_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1492_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1492_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1492_p_ce : OUT STD_LOGIC;
    grp_fu_1496_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1496_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1496_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1496_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1496_p_ce : OUT STD_LOGIC;
    grp_fu_1500_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1500_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1500_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1500_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1500_p_ce : OUT STD_LOGIC;
    grp_fu_1504_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1504_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1504_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1504_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1504_p_ce : OUT STD_LOGIC;
    grp_fu_1508_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1508_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1508_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1508_p_ce : OUT STD_LOGIC;
    grp_fu_1512_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1512_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1512_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1512_p_ce : OUT STD_LOGIC;
    grp_fu_1516_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1516_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1516_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1516_p_ce : OUT STD_LOGIC;
    grp_fu_1520_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1520_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1520_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1520_p_ce : OUT STD_LOGIC;
    grp_fu_1524_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1524_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1524_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1524_p_ce : OUT STD_LOGIC;
    grp_fu_1528_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1528_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1528_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1528_p_ce : OUT STD_LOGIC;
    grp_fu_1532_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1532_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1532_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1532_p_ce : OUT STD_LOGIC;
    grp_fu_1536_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1536_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1536_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1536_p_ce : OUT STD_LOGIC;
    grp_fu_1540_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1540_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1540_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1540_p_ce : OUT STD_LOGIC;
    grp_fu_1544_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1544_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1544_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1544_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1544_p_ce : OUT STD_LOGIC );
end;


architecture behav of DNN_DNN_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_25_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_3F1EE894 : STD_LOGIC_VECTOR (31 downto 0) := "00111111000111101110100010010100";
    constant ap_const_lv32_3FA69CD2 : STD_LOGIC_VECTOR (31 downto 0) := "00111111101001101001110011010010";
    constant ap_const_lv32_3FA891FC : STD_LOGIC_VECTOR (31 downto 0) := "00111111101010001001000111111100";
    constant ap_const_lv32_3F709A3B : STD_LOGIC_VECTOR (31 downto 0) := "00111111011100001001101000111011";
    constant ap_const_lv32_400F5B8A : STD_LOGIC_VECTOR (31 downto 0) := "01000000000011110101101110001010";
    constant ap_const_lv32_3F911723 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100100010001011100100011";
    constant ap_const_lv32_3FAD616D : STD_LOGIC_VECTOR (31 downto 0) := "00111111101011010110000101101101";
    constant ap_const_lv32_3FA2DC1B : STD_LOGIC_VECTOR (31 downto 0) := "00111111101000101101110000011011";
    constant ap_const_lv32_3F273774 : STD_LOGIC_VECTOR (31 downto 0) := "00111111001001110011011101110100";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter29 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter30 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter31 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter21 : BOOLEAN;
    signal ap_block_state23_pp0_stage0_iter22 : BOOLEAN;
    signal ap_block_state24_pp0_stage0_iter23 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter24 : BOOLEAN;
    signal ap_block_state26_pp0_stage0_iter25 : BOOLEAN;
    signal ap_block_state27_pp0_stage0_iter26 : BOOLEAN;
    signal ap_block_state28_pp0_stage0_iter27 : BOOLEAN;
    signal ap_block_state29_pp0_stage0_iter28 : BOOLEAN;
    signal ap_block_state30_pp0_stage0_iter29 : BOOLEAN;
    signal ap_block_state31_pp0_stage0_iter30 : BOOLEAN;
    signal ap_block_state32_pp0_stage0_iter31 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln24_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln33_fu_528_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter6_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter7_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter8_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter9_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter10_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter11_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter12_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter13_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter14_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter15_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter16_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter17_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter18_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter19_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter20_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter21_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter22_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter23_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter24_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter25_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter26_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter27_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter28_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter29_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln33_reg_728_pp0_iter30_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal temp_input_load_2_reg_773 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_2_reg_773_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_2_reg_773_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_2_reg_773_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_2_reg_773_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_2_reg_773_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_3_reg_778 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_3_reg_778_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_3_reg_778_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_3_reg_778_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_3_reg_778_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_3_reg_778_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_3_reg_778_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_3_reg_778_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_3_reg_778_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_4_reg_783 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_4_reg_783_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_4_reg_783_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_4_reg_783_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_4_reg_783_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_4_reg_783_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_4_reg_783_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_4_reg_783_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_4_reg_783_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_4_reg_783_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_4_reg_783_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_4_reg_783_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter13_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter14_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_5_reg_788_pp0_iter15_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter13_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter14_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter15_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter16_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter17_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_6_reg_793_pp0_iter18_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter13_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter14_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter15_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter16_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter17_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter18_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter19_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter20_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_7_reg_798_pp0_iter21_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter13_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter14_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter15_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter16_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter17_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter18_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter19_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter20_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter21_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter22_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter23_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_input_load_8_reg_803_pp0_iter24_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul21_i_reg_808 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul21_i_0_1_reg_813 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul21_i_0_1_reg_813_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul21_i_0_1_reg_813_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul21_i_0_1_reg_813_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_reg_818 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_0_1_reg_823 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul21_i_0_2_reg_828 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_0_2_reg_833 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul21_i_1_reg_838 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_1_reg_843 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul21_i_1_1_reg_848 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_1_1_reg_853 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul21_i_1_2_reg_858 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_1_2_reg_863 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul21_i_2_reg_868 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_2_reg_873 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul21_i_2_1_reg_878 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_2_1_reg_883 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul21_i_2_2_reg_888 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_2_2_reg_893 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_2_2_reg_893_pp0_iter30_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln29_5_fu_501_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln29_6_fu_512_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln29_7_fu_523_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln29_9_fu_550_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln29_10_fu_561_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln29_11_fu_572_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln29_13_fu_593_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln29_14_fu_604_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln29_15_fu_615_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln33_fu_635_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_82 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln29_fu_534_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_fu_86 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln24_1_fu_361_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten10_fu_90 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_indvar_flatten10_load : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln24_1_fu_338_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln25_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_326_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln29_fu_369_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_389_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl_cast_fu_381_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln29_fu_397_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_mid1_fu_407_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln24_2_fu_413_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_9_fu_429_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl2_cast_fu_421_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln29_1_fu_437_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln24_3_fu_447_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln24_fu_455_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_20_fu_469_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_461_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln29_2_fu_477_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln24_fu_353_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln29_2_fu_401_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln29_4_fu_491_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_5_fu_495_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_3_fu_441_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_6_fu_506_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_4_fu_481_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_7_fu_517_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl_cast1_fu_373_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln29_3_fu_487_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln29_8_fu_540_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_8_fu_544_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_9_fu_555_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_10_fu_566_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_1_fu_577_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln29_12_fu_583_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_11_fu_587_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_12_fu_598_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_13_fu_609_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal bitcast_ln7_fu_639_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_642_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln7_fu_652_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln7_1_fu_662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln7_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln7_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter27_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter28_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter29_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter30_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component DNN_fadd_32ns_32ns_32_3_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component DNN_fmul_32ns_32ns_32_2_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component DNN_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component DNN_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component DNN_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter30_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter29_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter30_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter30 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter31_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter31 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln24_fu_332_p2 = ap_const_lv1_0))) then 
                    i_fu_86 <= select_ln24_1_fu_361_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_86 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten10_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln24_fu_332_p2 = ap_const_lv1_0))) then 
                    indvar_flatten10_fu_90 <= add_ln24_1_fu_338_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten10_fu_90 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln24_fu_332_p2 = ap_const_lv1_0))) then 
                    j_fu_82 <= add_ln29_fu_534_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_82 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln24_fu_332_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln33_reg_728 <= add_ln33_fu_528_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln33_reg_728_pp0_iter10_reg <= add_ln33_reg_728_pp0_iter9_reg;
                add_ln33_reg_728_pp0_iter11_reg <= add_ln33_reg_728_pp0_iter10_reg;
                add_ln33_reg_728_pp0_iter12_reg <= add_ln33_reg_728_pp0_iter11_reg;
                add_ln33_reg_728_pp0_iter13_reg <= add_ln33_reg_728_pp0_iter12_reg;
                add_ln33_reg_728_pp0_iter14_reg <= add_ln33_reg_728_pp0_iter13_reg;
                add_ln33_reg_728_pp0_iter15_reg <= add_ln33_reg_728_pp0_iter14_reg;
                add_ln33_reg_728_pp0_iter16_reg <= add_ln33_reg_728_pp0_iter15_reg;
                add_ln33_reg_728_pp0_iter17_reg <= add_ln33_reg_728_pp0_iter16_reg;
                add_ln33_reg_728_pp0_iter18_reg <= add_ln33_reg_728_pp0_iter17_reg;
                add_ln33_reg_728_pp0_iter19_reg <= add_ln33_reg_728_pp0_iter18_reg;
                add_ln33_reg_728_pp0_iter20_reg <= add_ln33_reg_728_pp0_iter19_reg;
                add_ln33_reg_728_pp0_iter21_reg <= add_ln33_reg_728_pp0_iter20_reg;
                add_ln33_reg_728_pp0_iter22_reg <= add_ln33_reg_728_pp0_iter21_reg;
                add_ln33_reg_728_pp0_iter23_reg <= add_ln33_reg_728_pp0_iter22_reg;
                add_ln33_reg_728_pp0_iter24_reg <= add_ln33_reg_728_pp0_iter23_reg;
                add_ln33_reg_728_pp0_iter25_reg <= add_ln33_reg_728_pp0_iter24_reg;
                add_ln33_reg_728_pp0_iter26_reg <= add_ln33_reg_728_pp0_iter25_reg;
                add_ln33_reg_728_pp0_iter27_reg <= add_ln33_reg_728_pp0_iter26_reg;
                add_ln33_reg_728_pp0_iter28_reg <= add_ln33_reg_728_pp0_iter27_reg;
                add_ln33_reg_728_pp0_iter29_reg <= add_ln33_reg_728_pp0_iter28_reg;
                add_ln33_reg_728_pp0_iter2_reg <= add_ln33_reg_728_pp0_iter1_reg;
                add_ln33_reg_728_pp0_iter30_reg <= add_ln33_reg_728_pp0_iter29_reg;
                add_ln33_reg_728_pp0_iter3_reg <= add_ln33_reg_728_pp0_iter2_reg;
                add_ln33_reg_728_pp0_iter4_reg <= add_ln33_reg_728_pp0_iter3_reg;
                add_ln33_reg_728_pp0_iter5_reg <= add_ln33_reg_728_pp0_iter4_reg;
                add_ln33_reg_728_pp0_iter6_reg <= add_ln33_reg_728_pp0_iter5_reg;
                add_ln33_reg_728_pp0_iter7_reg <= add_ln33_reg_728_pp0_iter6_reg;
                add_ln33_reg_728_pp0_iter8_reg <= add_ln33_reg_728_pp0_iter7_reg;
                add_ln33_reg_728_pp0_iter9_reg <= add_ln33_reg_728_pp0_iter8_reg;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
                ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
                ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
                ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                mul21_i_0_1_reg_813 <= grp_fu_1512_p_dout0;
                mul21_i_0_1_reg_813_pp0_iter3_reg <= mul21_i_0_1_reg_813;
                mul21_i_0_1_reg_813_pp0_iter4_reg <= mul21_i_0_1_reg_813_pp0_iter3_reg;
                mul21_i_0_1_reg_813_pp0_iter5_reg <= mul21_i_0_1_reg_813_pp0_iter4_reg;
                mul21_i_0_2_reg_828 <= grp_fu_1516_p_dout0;
                mul21_i_1_1_reg_848 <= grp_fu_1524_p_dout0;
                mul21_i_1_2_reg_858 <= grp_fu_1528_p_dout0;
                mul21_i_1_reg_838 <= grp_fu_1520_p_dout0;
                mul21_i_2_1_reg_878 <= grp_fu_1536_p_dout0;
                mul21_i_2_2_reg_888 <= grp_fu_1540_p_dout0;
                mul21_i_2_reg_868 <= grp_fu_1532_p_dout0;
                mul21_i_reg_808 <= grp_fu_1508_p_dout0;
                sum_1_0_1_reg_823 <= grp_fu_1476_p_dout0;
                sum_1_0_2_reg_833 <= grp_fu_1480_p_dout0;
                sum_1_1_1_reg_853 <= grp_fu_1488_p_dout0;
                sum_1_1_2_reg_863 <= grp_fu_1492_p_dout0;
                sum_1_1_reg_843 <= grp_fu_1484_p_dout0;
                sum_1_2_1_reg_883 <= grp_fu_1500_p_dout0;
                sum_1_2_2_reg_893 <= grp_fu_1504_p_dout0;
                sum_1_2_2_reg_893_pp0_iter30_reg <= sum_1_2_2_reg_893;
                sum_1_2_reg_873 <= grp_fu_1496_p_dout0;
                sum_1_reg_818 <= grp_fu_1472_p_dout0;
                temp_input_load_2_reg_773_pp0_iter2_reg <= temp_input_load_2_reg_773;
                temp_input_load_2_reg_773_pp0_iter3_reg <= temp_input_load_2_reg_773_pp0_iter2_reg;
                temp_input_load_2_reg_773_pp0_iter4_reg <= temp_input_load_2_reg_773_pp0_iter3_reg;
                temp_input_load_2_reg_773_pp0_iter5_reg <= temp_input_load_2_reg_773_pp0_iter4_reg;
                temp_input_load_2_reg_773_pp0_iter6_reg <= temp_input_load_2_reg_773_pp0_iter5_reg;
                temp_input_load_3_reg_778_pp0_iter2_reg <= temp_input_load_3_reg_778;
                temp_input_load_3_reg_778_pp0_iter3_reg <= temp_input_load_3_reg_778_pp0_iter2_reg;
                temp_input_load_3_reg_778_pp0_iter4_reg <= temp_input_load_3_reg_778_pp0_iter3_reg;
                temp_input_load_3_reg_778_pp0_iter5_reg <= temp_input_load_3_reg_778_pp0_iter4_reg;
                temp_input_load_3_reg_778_pp0_iter6_reg <= temp_input_load_3_reg_778_pp0_iter5_reg;
                temp_input_load_3_reg_778_pp0_iter7_reg <= temp_input_load_3_reg_778_pp0_iter6_reg;
                temp_input_load_3_reg_778_pp0_iter8_reg <= temp_input_load_3_reg_778_pp0_iter7_reg;
                temp_input_load_3_reg_778_pp0_iter9_reg <= temp_input_load_3_reg_778_pp0_iter8_reg;
                temp_input_load_4_reg_783_pp0_iter10_reg <= temp_input_load_4_reg_783_pp0_iter9_reg;
                temp_input_load_4_reg_783_pp0_iter11_reg <= temp_input_load_4_reg_783_pp0_iter10_reg;
                temp_input_load_4_reg_783_pp0_iter12_reg <= temp_input_load_4_reg_783_pp0_iter11_reg;
                temp_input_load_4_reg_783_pp0_iter2_reg <= temp_input_load_4_reg_783;
                temp_input_load_4_reg_783_pp0_iter3_reg <= temp_input_load_4_reg_783_pp0_iter2_reg;
                temp_input_load_4_reg_783_pp0_iter4_reg <= temp_input_load_4_reg_783_pp0_iter3_reg;
                temp_input_load_4_reg_783_pp0_iter5_reg <= temp_input_load_4_reg_783_pp0_iter4_reg;
                temp_input_load_4_reg_783_pp0_iter6_reg <= temp_input_load_4_reg_783_pp0_iter5_reg;
                temp_input_load_4_reg_783_pp0_iter7_reg <= temp_input_load_4_reg_783_pp0_iter6_reg;
                temp_input_load_4_reg_783_pp0_iter8_reg <= temp_input_load_4_reg_783_pp0_iter7_reg;
                temp_input_load_4_reg_783_pp0_iter9_reg <= temp_input_load_4_reg_783_pp0_iter8_reg;
                temp_input_load_5_reg_788_pp0_iter10_reg <= temp_input_load_5_reg_788_pp0_iter9_reg;
                temp_input_load_5_reg_788_pp0_iter11_reg <= temp_input_load_5_reg_788_pp0_iter10_reg;
                temp_input_load_5_reg_788_pp0_iter12_reg <= temp_input_load_5_reg_788_pp0_iter11_reg;
                temp_input_load_5_reg_788_pp0_iter13_reg <= temp_input_load_5_reg_788_pp0_iter12_reg;
                temp_input_load_5_reg_788_pp0_iter14_reg <= temp_input_load_5_reg_788_pp0_iter13_reg;
                temp_input_load_5_reg_788_pp0_iter15_reg <= temp_input_load_5_reg_788_pp0_iter14_reg;
                temp_input_load_5_reg_788_pp0_iter2_reg <= temp_input_load_5_reg_788;
                temp_input_load_5_reg_788_pp0_iter3_reg <= temp_input_load_5_reg_788_pp0_iter2_reg;
                temp_input_load_5_reg_788_pp0_iter4_reg <= temp_input_load_5_reg_788_pp0_iter3_reg;
                temp_input_load_5_reg_788_pp0_iter5_reg <= temp_input_load_5_reg_788_pp0_iter4_reg;
                temp_input_load_5_reg_788_pp0_iter6_reg <= temp_input_load_5_reg_788_pp0_iter5_reg;
                temp_input_load_5_reg_788_pp0_iter7_reg <= temp_input_load_5_reg_788_pp0_iter6_reg;
                temp_input_load_5_reg_788_pp0_iter8_reg <= temp_input_load_5_reg_788_pp0_iter7_reg;
                temp_input_load_5_reg_788_pp0_iter9_reg <= temp_input_load_5_reg_788_pp0_iter8_reg;
                temp_input_load_6_reg_793_pp0_iter10_reg <= temp_input_load_6_reg_793_pp0_iter9_reg;
                temp_input_load_6_reg_793_pp0_iter11_reg <= temp_input_load_6_reg_793_pp0_iter10_reg;
                temp_input_load_6_reg_793_pp0_iter12_reg <= temp_input_load_6_reg_793_pp0_iter11_reg;
                temp_input_load_6_reg_793_pp0_iter13_reg <= temp_input_load_6_reg_793_pp0_iter12_reg;
                temp_input_load_6_reg_793_pp0_iter14_reg <= temp_input_load_6_reg_793_pp0_iter13_reg;
                temp_input_load_6_reg_793_pp0_iter15_reg <= temp_input_load_6_reg_793_pp0_iter14_reg;
                temp_input_load_6_reg_793_pp0_iter16_reg <= temp_input_load_6_reg_793_pp0_iter15_reg;
                temp_input_load_6_reg_793_pp0_iter17_reg <= temp_input_load_6_reg_793_pp0_iter16_reg;
                temp_input_load_6_reg_793_pp0_iter18_reg <= temp_input_load_6_reg_793_pp0_iter17_reg;
                temp_input_load_6_reg_793_pp0_iter2_reg <= temp_input_load_6_reg_793;
                temp_input_load_6_reg_793_pp0_iter3_reg <= temp_input_load_6_reg_793_pp0_iter2_reg;
                temp_input_load_6_reg_793_pp0_iter4_reg <= temp_input_load_6_reg_793_pp0_iter3_reg;
                temp_input_load_6_reg_793_pp0_iter5_reg <= temp_input_load_6_reg_793_pp0_iter4_reg;
                temp_input_load_6_reg_793_pp0_iter6_reg <= temp_input_load_6_reg_793_pp0_iter5_reg;
                temp_input_load_6_reg_793_pp0_iter7_reg <= temp_input_load_6_reg_793_pp0_iter6_reg;
                temp_input_load_6_reg_793_pp0_iter8_reg <= temp_input_load_6_reg_793_pp0_iter7_reg;
                temp_input_load_6_reg_793_pp0_iter9_reg <= temp_input_load_6_reg_793_pp0_iter8_reg;
                temp_input_load_7_reg_798_pp0_iter10_reg <= temp_input_load_7_reg_798_pp0_iter9_reg;
                temp_input_load_7_reg_798_pp0_iter11_reg <= temp_input_load_7_reg_798_pp0_iter10_reg;
                temp_input_load_7_reg_798_pp0_iter12_reg <= temp_input_load_7_reg_798_pp0_iter11_reg;
                temp_input_load_7_reg_798_pp0_iter13_reg <= temp_input_load_7_reg_798_pp0_iter12_reg;
                temp_input_load_7_reg_798_pp0_iter14_reg <= temp_input_load_7_reg_798_pp0_iter13_reg;
                temp_input_load_7_reg_798_pp0_iter15_reg <= temp_input_load_7_reg_798_pp0_iter14_reg;
                temp_input_load_7_reg_798_pp0_iter16_reg <= temp_input_load_7_reg_798_pp0_iter15_reg;
                temp_input_load_7_reg_798_pp0_iter17_reg <= temp_input_load_7_reg_798_pp0_iter16_reg;
                temp_input_load_7_reg_798_pp0_iter18_reg <= temp_input_load_7_reg_798_pp0_iter17_reg;
                temp_input_load_7_reg_798_pp0_iter19_reg <= temp_input_load_7_reg_798_pp0_iter18_reg;
                temp_input_load_7_reg_798_pp0_iter20_reg <= temp_input_load_7_reg_798_pp0_iter19_reg;
                temp_input_load_7_reg_798_pp0_iter21_reg <= temp_input_load_7_reg_798_pp0_iter20_reg;
                temp_input_load_7_reg_798_pp0_iter2_reg <= temp_input_load_7_reg_798;
                temp_input_load_7_reg_798_pp0_iter3_reg <= temp_input_load_7_reg_798_pp0_iter2_reg;
                temp_input_load_7_reg_798_pp0_iter4_reg <= temp_input_load_7_reg_798_pp0_iter3_reg;
                temp_input_load_7_reg_798_pp0_iter5_reg <= temp_input_load_7_reg_798_pp0_iter4_reg;
                temp_input_load_7_reg_798_pp0_iter6_reg <= temp_input_load_7_reg_798_pp0_iter5_reg;
                temp_input_load_7_reg_798_pp0_iter7_reg <= temp_input_load_7_reg_798_pp0_iter6_reg;
                temp_input_load_7_reg_798_pp0_iter8_reg <= temp_input_load_7_reg_798_pp0_iter7_reg;
                temp_input_load_7_reg_798_pp0_iter9_reg <= temp_input_load_7_reg_798_pp0_iter8_reg;
                temp_input_load_8_reg_803_pp0_iter10_reg <= temp_input_load_8_reg_803_pp0_iter9_reg;
                temp_input_load_8_reg_803_pp0_iter11_reg <= temp_input_load_8_reg_803_pp0_iter10_reg;
                temp_input_load_8_reg_803_pp0_iter12_reg <= temp_input_load_8_reg_803_pp0_iter11_reg;
                temp_input_load_8_reg_803_pp0_iter13_reg <= temp_input_load_8_reg_803_pp0_iter12_reg;
                temp_input_load_8_reg_803_pp0_iter14_reg <= temp_input_load_8_reg_803_pp0_iter13_reg;
                temp_input_load_8_reg_803_pp0_iter15_reg <= temp_input_load_8_reg_803_pp0_iter14_reg;
                temp_input_load_8_reg_803_pp0_iter16_reg <= temp_input_load_8_reg_803_pp0_iter15_reg;
                temp_input_load_8_reg_803_pp0_iter17_reg <= temp_input_load_8_reg_803_pp0_iter16_reg;
                temp_input_load_8_reg_803_pp0_iter18_reg <= temp_input_load_8_reg_803_pp0_iter17_reg;
                temp_input_load_8_reg_803_pp0_iter19_reg <= temp_input_load_8_reg_803_pp0_iter18_reg;
                temp_input_load_8_reg_803_pp0_iter20_reg <= temp_input_load_8_reg_803_pp0_iter19_reg;
                temp_input_load_8_reg_803_pp0_iter21_reg <= temp_input_load_8_reg_803_pp0_iter20_reg;
                temp_input_load_8_reg_803_pp0_iter22_reg <= temp_input_load_8_reg_803_pp0_iter21_reg;
                temp_input_load_8_reg_803_pp0_iter23_reg <= temp_input_load_8_reg_803_pp0_iter22_reg;
                temp_input_load_8_reg_803_pp0_iter24_reg <= temp_input_load_8_reg_803_pp0_iter23_reg;
                temp_input_load_8_reg_803_pp0_iter2_reg <= temp_input_load_8_reg_803;
                temp_input_load_8_reg_803_pp0_iter3_reg <= temp_input_load_8_reg_803_pp0_iter2_reg;
                temp_input_load_8_reg_803_pp0_iter4_reg <= temp_input_load_8_reg_803_pp0_iter3_reg;
                temp_input_load_8_reg_803_pp0_iter5_reg <= temp_input_load_8_reg_803_pp0_iter4_reg;
                temp_input_load_8_reg_803_pp0_iter6_reg <= temp_input_load_8_reg_803_pp0_iter5_reg;
                temp_input_load_8_reg_803_pp0_iter7_reg <= temp_input_load_8_reg_803_pp0_iter6_reg;
                temp_input_load_8_reg_803_pp0_iter8_reg <= temp_input_load_8_reg_803_pp0_iter7_reg;
                temp_input_load_8_reg_803_pp0_iter9_reg <= temp_input_load_8_reg_803_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln33_reg_728_pp0_iter1_reg <= add_ln33_reg_728;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                temp_input_load_2_reg_773 <= temp_input_q6;
                temp_input_load_3_reg_778 <= temp_input_q5;
                temp_input_load_4_reg_783 <= temp_input_q4;
                temp_input_load_5_reg_788 <= temp_input_q3;
                temp_input_load_6_reg_793 <= temp_input_q2;
                temp_input_load_7_reg_798 <= temp_input_q1;
                temp_input_load_8_reg_803 <= temp_input_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln24_1_fu_338_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten10_load) + unsigned(ap_const_lv7_1));
    add_ln24_fu_455_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(select_ln24_3_fu_447_p3));
    add_ln29_10_fu_566_p2 <= std_logic_vector(unsigned(add_ln29_4_fu_481_p2) + unsigned(zext_ln29_8_fu_540_p1));
    add_ln29_11_fu_587_p2 <= std_logic_vector(unsigned(add_ln29_2_fu_401_p2) + unsigned(zext_ln29_12_fu_583_p1));
    add_ln29_12_fu_598_p2 <= std_logic_vector(unsigned(add_ln29_3_fu_441_p2) + unsigned(zext_ln29_12_fu_583_p1));
    add_ln29_13_fu_609_p2 <= std_logic_vector(unsigned(add_ln29_4_fu_481_p2) + unsigned(zext_ln29_12_fu_583_p1));
    add_ln29_1_fu_577_p2 <= std_logic_vector(unsigned(select_ln24_fu_353_p3) + unsigned(ap_const_lv4_2));
    add_ln29_2_fu_401_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_381_p3) + unsigned(zext_ln29_fu_397_p1));
    add_ln29_3_fu_441_p2 <= std_logic_vector(unsigned(p_shl2_cast_fu_421_p3) + unsigned(zext_ln29_1_fu_437_p1));
    add_ln29_4_fu_481_p2 <= std_logic_vector(unsigned(tmp_s_fu_461_p3) + unsigned(zext_ln29_2_fu_477_p1));
    add_ln29_5_fu_495_p2 <= std_logic_vector(unsigned(add_ln29_2_fu_401_p2) + unsigned(zext_ln29_4_fu_491_p1));
    add_ln29_6_fu_506_p2 <= std_logic_vector(unsigned(add_ln29_3_fu_441_p2) + unsigned(zext_ln29_4_fu_491_p1));
    add_ln29_7_fu_517_p2 <= std_logic_vector(unsigned(add_ln29_4_fu_481_p2) + unsigned(zext_ln29_4_fu_491_p1));
    add_ln29_8_fu_544_p2 <= std_logic_vector(unsigned(add_ln29_2_fu_401_p2) + unsigned(zext_ln29_8_fu_540_p1));
    add_ln29_9_fu_555_p2 <= std_logic_vector(unsigned(add_ln29_3_fu_441_p2) + unsigned(zext_ln29_8_fu_540_p1));
    add_ln29_fu_534_p2 <= std_logic_vector(unsigned(select_ln24_fu_353_p3) + unsigned(ap_const_lv4_1));
    add_ln33_fu_528_p2 <= std_logic_vector(unsigned(p_shl_cast1_fu_373_p3) + unsigned(zext_ln29_3_fu_487_p1));
    and_ln7_fu_674_p2 <= (or_ln7_fu_668_p2 and grp_fu_1544_p_dout0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage0_iter22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage0_iter23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage0_iter25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state27_pp0_stage0_iter26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state28_pp0_stage0_iter27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state29_pp0_stage0_iter28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state30_pp0_stage0_iter29 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state31_pp0_stage0_iter30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state32_pp0_stage0_iter31 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln24_fu_332_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln24_fu_332_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter30_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter30_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29, ap_enable_reg_pp0_iter30, ap_enable_reg_pp0_iter31)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter31 = ap_const_logic_0) and (ap_enable_reg_pp0_iter30 = ap_const_logic_0) and (ap_enable_reg_pp0_iter29 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_86)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_86;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten10_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten10_fu_90)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten10_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten10_load <= indvar_flatten10_fu_90;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_82, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_82;
        end if; 
    end process;

    bitcast_ln7_fu_639_p1 <= sum_1_2_2_reg_893_pp0_iter30_reg;
    conv1_output_address0 <= zext_ln33_fu_635_p1(6 - 1 downto 0);

    conv1_output_ce0_assign_proc : process(ap_enable_reg_pp0_iter31, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter31 = ap_const_logic_1))) then 
            conv1_output_ce0 <= ap_const_logic_1;
        else 
            conv1_output_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    conv1_output_d0 <= 
        ap_const_lv32_0 when (and_ln7_fu_674_p2(0) = '1') else 
        sum_1_2_2_reg_893_pp0_iter30_reg;

    conv1_output_we0_assign_proc : process(ap_enable_reg_pp0_iter31, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter31 = ap_const_logic_1))) then 
            conv1_output_we0 <= ap_const_logic_1;
        else 
            conv1_output_we0 <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_326_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv4_1));
    grp_fu_1472_p_ce <= ap_const_logic_1;
    grp_fu_1472_p_din0 <= mul21_i_reg_808;
    grp_fu_1472_p_din1 <= ap_const_lv32_0;
    grp_fu_1472_p_opcode <= ap_const_lv2_0;
    grp_fu_1476_p_ce <= ap_const_logic_1;
    grp_fu_1476_p_din0 <= sum_1_reg_818;
    grp_fu_1476_p_din1 <= mul21_i_0_1_reg_813_pp0_iter5_reg;
    grp_fu_1476_p_opcode <= ap_const_lv2_0;
    grp_fu_1480_p_ce <= ap_const_logic_1;
    grp_fu_1480_p_din0 <= sum_1_0_1_reg_823;
    grp_fu_1480_p_din1 <= mul21_i_0_2_reg_828;
    grp_fu_1480_p_opcode <= ap_const_lv2_0;
    grp_fu_1484_p_ce <= ap_const_logic_1;
    grp_fu_1484_p_din0 <= sum_1_0_2_reg_833;
    grp_fu_1484_p_din1 <= mul21_i_1_reg_838;
    grp_fu_1484_p_opcode <= ap_const_lv2_0;
    grp_fu_1488_p_ce <= ap_const_logic_1;
    grp_fu_1488_p_din0 <= sum_1_1_reg_843;
    grp_fu_1488_p_din1 <= mul21_i_1_1_reg_848;
    grp_fu_1488_p_opcode <= ap_const_lv2_0;
    grp_fu_1492_p_ce <= ap_const_logic_1;
    grp_fu_1492_p_din0 <= sum_1_1_1_reg_853;
    grp_fu_1492_p_din1 <= mul21_i_1_2_reg_858;
    grp_fu_1492_p_opcode <= ap_const_lv2_0;
    grp_fu_1496_p_ce <= ap_const_logic_1;
    grp_fu_1496_p_din0 <= sum_1_1_2_reg_863;
    grp_fu_1496_p_din1 <= mul21_i_2_reg_868;
    grp_fu_1496_p_opcode <= ap_const_lv2_0;
    grp_fu_1500_p_ce <= ap_const_logic_1;
    grp_fu_1500_p_din0 <= sum_1_2_reg_873;
    grp_fu_1500_p_din1 <= mul21_i_2_1_reg_878;
    grp_fu_1500_p_opcode <= ap_const_lv2_0;
    grp_fu_1504_p_ce <= ap_const_logic_1;
    grp_fu_1504_p_din0 <= sum_1_2_1_reg_883;
    grp_fu_1504_p_din1 <= mul21_i_2_2_reg_888;
    grp_fu_1504_p_opcode <= ap_const_lv2_0;
    grp_fu_1508_p_ce <= ap_const_logic_1;
    grp_fu_1508_p_din0 <= temp_input_q8;
    grp_fu_1508_p_din1 <= ap_const_lv32_3F1EE894;
    grp_fu_1512_p_ce <= ap_const_logic_1;
    grp_fu_1512_p_din0 <= temp_input_q7;
    grp_fu_1512_p_din1 <= ap_const_lv32_3FA69CD2;
    grp_fu_1516_p_ce <= ap_const_logic_1;
    grp_fu_1516_p_din0 <= temp_input_load_2_reg_773_pp0_iter6_reg;
    grp_fu_1516_p_din1 <= ap_const_lv32_3FA891FC;
    grp_fu_1520_p_ce <= ap_const_logic_1;
    grp_fu_1520_p_din0 <= temp_input_load_3_reg_778_pp0_iter9_reg;
    grp_fu_1520_p_din1 <= ap_const_lv32_3F709A3B;
    grp_fu_1524_p_ce <= ap_const_logic_1;
    grp_fu_1524_p_din0 <= temp_input_load_4_reg_783_pp0_iter12_reg;
    grp_fu_1524_p_din1 <= ap_const_lv32_400F5B8A;
    grp_fu_1528_p_ce <= ap_const_logic_1;
    grp_fu_1528_p_din0 <= temp_input_load_5_reg_788_pp0_iter15_reg;
    grp_fu_1528_p_din1 <= ap_const_lv32_3F911723;
    grp_fu_1532_p_ce <= ap_const_logic_1;
    grp_fu_1532_p_din0 <= temp_input_load_6_reg_793_pp0_iter18_reg;
    grp_fu_1532_p_din1 <= ap_const_lv32_3FAD616D;
    grp_fu_1536_p_ce <= ap_const_logic_1;
    grp_fu_1536_p_din0 <= temp_input_load_7_reg_798_pp0_iter21_reg;
    grp_fu_1536_p_din1 <= ap_const_lv32_3FA2DC1B;
    grp_fu_1540_p_ce <= ap_const_logic_1;
    grp_fu_1540_p_din0 <= temp_input_load_8_reg_803_pp0_iter24_reg;
    grp_fu_1540_p_din1 <= ap_const_lv32_3F273774;
    grp_fu_1544_p_ce <= ap_const_logic_1;
    grp_fu_1544_p_din0 <= sum_1_2_2_reg_893;
    grp_fu_1544_p_din1 <= ap_const_lv32_0;
    grp_fu_1544_p_opcode <= ap_const_lv5_4;
    icmp_ln24_fu_332_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten10_load = ap_const_lv7_40) else "0";
    icmp_ln25_fu_347_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv4_8) else "0";
    icmp_ln7_1_fu_662_p2 <= "1" when (trunc_ln7_fu_652_p1 = ap_const_lv23_0) else "0";
    icmp_ln7_fu_656_p2 <= "0" when (tmp_1_fu_642_p4 = ap_const_lv8_FF) else "1";
    or_ln7_fu_668_p2 <= (icmp_ln7_fu_656_p2 or icmp_ln7_1_fu_662_p2);
    p_mid1_fu_407_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv4_2));
    p_shl2_cast_fu_421_p3 <= (select_ln24_2_fu_413_p3 & ap_const_lv3_0);
    p_shl_cast1_fu_373_p3 <= (trunc_ln29_fu_369_p1 & ap_const_lv3_0);
    p_shl_cast_fu_381_p3 <= (select_ln24_1_fu_361_p3 & ap_const_lv3_0);
    select_ln24_1_fu_361_p3 <= 
        empty_fu_326_p2 when (icmp_ln25_fu_347_p2(0) = '1') else 
        ap_sig_allocacmp_i_1;
    select_ln24_2_fu_413_p3 <= 
        p_mid1_fu_407_p2 when (icmp_ln25_fu_347_p2(0) = '1') else 
        empty_fu_326_p2;
    select_ln24_3_fu_447_p3 <= 
        ap_const_lv4_3 when (icmp_ln25_fu_347_p2(0) = '1') else 
        ap_const_lv4_2;
    select_ln24_fu_353_p3 <= 
        ap_const_lv4_0 when (icmp_ln25_fu_347_p2(0) = '1') else 
        ap_sig_allocacmp_j_load;
    temp_input_address0 <= zext_ln29_15_fu_615_p1(7 - 1 downto 0);
    temp_input_address1 <= zext_ln29_11_fu_572_p1(7 - 1 downto 0);
    temp_input_address2 <= zext_ln29_7_fu_523_p1(7 - 1 downto 0);
    temp_input_address3 <= zext_ln29_14_fu_604_p1(7 - 1 downto 0);
    temp_input_address4 <= zext_ln29_10_fu_561_p1(7 - 1 downto 0);
    temp_input_address5 <= zext_ln29_6_fu_512_p1(7 - 1 downto 0);
    temp_input_address6 <= zext_ln29_13_fu_593_p1(7 - 1 downto 0);
    temp_input_address7 <= zext_ln29_9_fu_550_p1(7 - 1 downto 0);
    temp_input_address8 <= zext_ln29_5_fu_501_p1(7 - 1 downto 0);

    temp_input_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            temp_input_ce0 <= ap_const_logic_1;
        else 
            temp_input_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    temp_input_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            temp_input_ce1 <= ap_const_logic_1;
        else 
            temp_input_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    temp_input_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            temp_input_ce2 <= ap_const_logic_1;
        else 
            temp_input_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    temp_input_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            temp_input_ce3 <= ap_const_logic_1;
        else 
            temp_input_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    temp_input_ce4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            temp_input_ce4 <= ap_const_logic_1;
        else 
            temp_input_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    temp_input_ce5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            temp_input_ce5 <= ap_const_logic_1;
        else 
            temp_input_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    temp_input_ce6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            temp_input_ce6 <= ap_const_logic_1;
        else 
            temp_input_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    temp_input_ce7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            temp_input_ce7 <= ap_const_logic_1;
        else 
            temp_input_ce7 <= ap_const_logic_0;
        end if; 
    end process;


    temp_input_ce8_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            temp_input_ce8 <= ap_const_logic_1;
        else 
            temp_input_ce8 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_642_p4 <= bitcast_ln7_fu_639_p1(30 downto 23);
    tmp_20_fu_469_p3 <= (add_ln24_fu_455_p2 & ap_const_lv1_0);
    tmp_9_fu_429_p3 <= (select_ln24_2_fu_413_p3 & ap_const_lv1_0);
    tmp_fu_389_p3 <= (select_ln24_1_fu_361_p3 & ap_const_lv1_0);
    tmp_s_fu_461_p3 <= (add_ln24_fu_455_p2 & ap_const_lv3_0);
    trunc_ln29_fu_369_p1 <= select_ln24_1_fu_361_p3(3 - 1 downto 0);
    trunc_ln7_fu_652_p1 <= bitcast_ln7_fu_639_p1(23 - 1 downto 0);
    zext_ln29_10_fu_561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_9_fu_555_p2),64));
    zext_ln29_11_fu_572_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_10_fu_566_p2),64));
    zext_ln29_12_fu_583_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_1_fu_577_p2),7));
    zext_ln29_13_fu_593_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_11_fu_587_p2),64));
    zext_ln29_14_fu_604_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_12_fu_598_p2),64));
    zext_ln29_15_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_13_fu_609_p2),64));
    zext_ln29_1_fu_437_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_429_p3),7));
    zext_ln29_2_fu_477_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_20_fu_469_p3),7));
    zext_ln29_3_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln24_fu_353_p3),6));
    zext_ln29_4_fu_491_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln24_fu_353_p3),7));
    zext_ln29_5_fu_501_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_5_fu_495_p2),64));
    zext_ln29_6_fu_512_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_6_fu_506_p2),64));
    zext_ln29_7_fu_523_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_7_fu_517_p2),64));
    zext_ln29_8_fu_540_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_fu_534_p2),7));
    zext_ln29_9_fu_550_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_8_fu_544_p2),64));
    zext_ln29_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_389_p3),7));
    zext_ln33_fu_635_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln33_reg_728_pp0_iter30_reg),64));
end behav;
