set_property PACKAGE_PIN R14 [get_ports led_ctrl1_0]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl1_0]
set_property PACKAGE_PIN P14 [get_ports led_ctrl2_0]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl2_0]
set_property PACKAGE_PIN N16 [get_ports led_ctrl3_0]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl3_0]
set_property PACKAGE_PIN M14 [get_ports led_ctrl4_0]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl4_0]
