// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module DNN_DNN_Pipeline_VITIS_LOOP_135_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fc1_output_load,
        fc1_output_load_1,
        fc1_output_load_2,
        fc1_output_load_3,
        fc1_output_load_4,
        fc1_output_load_5,
        fc1_output_load_6,
        fc1_output_load_7,
        fc1_output_load_8,
        fc1_output_load_9,
        fc1_output_load_10,
        fc1_output_load_11,
        fc1_output_load_12,
        fc1_output_load_13,
        fc1_output_load_14,
        fc1_output_load_15,
        fc2_output_address0,
        fc2_output_ce0,
        fc2_output_we0,
        fc2_output_d0,
        grp_fu_1472_p_din0,
        grp_fu_1472_p_din1,
        grp_fu_1472_p_opcode,
        grp_fu_1472_p_dout0,
        grp_fu_1472_p_ce,
        grp_fu_1476_p_din0,
        grp_fu_1476_p_din1,
        grp_fu_1476_p_opcode,
        grp_fu_1476_p_dout0,
        grp_fu_1476_p_ce,
        grp_fu_1480_p_din0,
        grp_fu_1480_p_din1,
        grp_fu_1480_p_opcode,
        grp_fu_1480_p_dout0,
        grp_fu_1480_p_ce,
        grp_fu_1484_p_din0,
        grp_fu_1484_p_din1,
        grp_fu_1484_p_opcode,
        grp_fu_1484_p_dout0,
        grp_fu_1484_p_ce,
        grp_fu_1488_p_din0,
        grp_fu_1488_p_din1,
        grp_fu_1488_p_opcode,
        grp_fu_1488_p_dout0,
        grp_fu_1488_p_ce,
        grp_fu_1492_p_din0,
        grp_fu_1492_p_din1,
        grp_fu_1492_p_opcode,
        grp_fu_1492_p_dout0,
        grp_fu_1492_p_ce,
        grp_fu_1496_p_din0,
        grp_fu_1496_p_din1,
        grp_fu_1496_p_opcode,
        grp_fu_1496_p_dout0,
        grp_fu_1496_p_ce,
        grp_fu_1500_p_din0,
        grp_fu_1500_p_din1,
        grp_fu_1500_p_opcode,
        grp_fu_1500_p_dout0,
        grp_fu_1500_p_ce,
        grp_fu_1504_p_din0,
        grp_fu_1504_p_din1,
        grp_fu_1504_p_opcode,
        grp_fu_1504_p_dout0,
        grp_fu_1504_p_ce,
        grp_fu_1556_p_din0,
        grp_fu_1556_p_din1,
        grp_fu_1556_p_opcode,
        grp_fu_1556_p_dout0,
        grp_fu_1556_p_ce,
        grp_fu_1560_p_din0,
        grp_fu_1560_p_din1,
        grp_fu_1560_p_opcode,
        grp_fu_1560_p_dout0,
        grp_fu_1560_p_ce,
        grp_fu_1564_p_din0,
        grp_fu_1564_p_din1,
        grp_fu_1564_p_opcode,
        grp_fu_1564_p_dout0,
        grp_fu_1564_p_ce,
        grp_fu_1568_p_din0,
        grp_fu_1568_p_din1,
        grp_fu_1568_p_opcode,
        grp_fu_1568_p_dout0,
        grp_fu_1568_p_ce,
        grp_fu_1572_p_din0,
        grp_fu_1572_p_din1,
        grp_fu_1572_p_opcode,
        grp_fu_1572_p_dout0,
        grp_fu_1572_p_ce,
        grp_fu_1576_p_din0,
        grp_fu_1576_p_din1,
        grp_fu_1576_p_opcode,
        grp_fu_1576_p_dout0,
        grp_fu_1576_p_ce,
        grp_fu_1580_p_din0,
        grp_fu_1580_p_din1,
        grp_fu_1580_p_opcode,
        grp_fu_1580_p_dout0,
        grp_fu_1580_p_ce,
        grp_fu_1508_p_din0,
        grp_fu_1508_p_din1,
        grp_fu_1508_p_dout0,
        grp_fu_1508_p_ce,
        grp_fu_1512_p_din0,
        grp_fu_1512_p_din1,
        grp_fu_1512_p_dout0,
        grp_fu_1512_p_ce,
        grp_fu_1516_p_din0,
        grp_fu_1516_p_din1,
        grp_fu_1516_p_dout0,
        grp_fu_1516_p_ce,
        grp_fu_1520_p_din0,
        grp_fu_1520_p_din1,
        grp_fu_1520_p_dout0,
        grp_fu_1520_p_ce,
        grp_fu_1524_p_din0,
        grp_fu_1524_p_din1,
        grp_fu_1524_p_dout0,
        grp_fu_1524_p_ce,
        grp_fu_1528_p_din0,
        grp_fu_1528_p_din1,
        grp_fu_1528_p_dout0,
        grp_fu_1528_p_ce,
        grp_fu_1532_p_din0,
        grp_fu_1532_p_din1,
        grp_fu_1532_p_dout0,
        grp_fu_1532_p_ce,
        grp_fu_1536_p_din0,
        grp_fu_1536_p_din1,
        grp_fu_1536_p_dout0,
        grp_fu_1536_p_ce,
        grp_fu_1540_p_din0,
        grp_fu_1540_p_din1,
        grp_fu_1540_p_dout0,
        grp_fu_1540_p_ce,
        grp_fu_1584_p_din0,
        grp_fu_1584_p_din1,
        grp_fu_1584_p_dout0,
        grp_fu_1584_p_ce,
        grp_fu_1588_p_din0,
        grp_fu_1588_p_din1,
        grp_fu_1588_p_dout0,
        grp_fu_1588_p_ce,
        grp_fu_1592_p_din0,
        grp_fu_1592_p_din1,
        grp_fu_1592_p_dout0,
        grp_fu_1592_p_ce,
        grp_fu_1596_p_din0,
        grp_fu_1596_p_din1,
        grp_fu_1596_p_dout0,
        grp_fu_1596_p_ce,
        grp_fu_1600_p_din0,
        grp_fu_1600_p_din1,
        grp_fu_1600_p_dout0,
        grp_fu_1600_p_ce,
        grp_fu_1604_p_din0,
        grp_fu_1604_p_din1,
        grp_fu_1604_p_dout0,
        grp_fu_1604_p_ce,
        grp_fu_1608_p_din0,
        grp_fu_1608_p_din1,
        grp_fu_1608_p_dout0,
        grp_fu_1608_p_ce,
        grp_fu_1544_p_din0,
        grp_fu_1544_p_din1,
        grp_fu_1544_p_opcode,
        grp_fu_1544_p_dout0,
        grp_fu_1544_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] fc1_output_load;
input  [31:0] fc1_output_load_1;
input  [31:0] fc1_output_load_2;
input  [31:0] fc1_output_load_3;
input  [31:0] fc1_output_load_4;
input  [31:0] fc1_output_load_5;
input  [31:0] fc1_output_load_6;
input  [31:0] fc1_output_load_7;
input  [31:0] fc1_output_load_8;
input  [31:0] fc1_output_load_9;
input  [31:0] fc1_output_load_10;
input  [31:0] fc1_output_load_11;
input  [31:0] fc1_output_load_12;
input  [31:0] fc1_output_load_13;
input  [31:0] fc1_output_load_14;
input  [31:0] fc1_output_load_15;
output  [3:0] fc2_output_address0;
output   fc2_output_ce0;
output   fc2_output_we0;
output  [31:0] fc2_output_d0;
output  [31:0] grp_fu_1472_p_din0;
output  [31:0] grp_fu_1472_p_din1;
output  [1:0] grp_fu_1472_p_opcode;
input  [31:0] grp_fu_1472_p_dout0;
output   grp_fu_1472_p_ce;
output  [31:0] grp_fu_1476_p_din0;
output  [31:0] grp_fu_1476_p_din1;
output  [1:0] grp_fu_1476_p_opcode;
input  [31:0] grp_fu_1476_p_dout0;
output   grp_fu_1476_p_ce;
output  [31:0] grp_fu_1480_p_din0;
output  [31:0] grp_fu_1480_p_din1;
output  [1:0] grp_fu_1480_p_opcode;
input  [31:0] grp_fu_1480_p_dout0;
output   grp_fu_1480_p_ce;
output  [31:0] grp_fu_1484_p_din0;
output  [31:0] grp_fu_1484_p_din1;
output  [1:0] grp_fu_1484_p_opcode;
input  [31:0] grp_fu_1484_p_dout0;
output   grp_fu_1484_p_ce;
output  [31:0] grp_fu_1488_p_din0;
output  [31:0] grp_fu_1488_p_din1;
output  [1:0] grp_fu_1488_p_opcode;
input  [31:0] grp_fu_1488_p_dout0;
output   grp_fu_1488_p_ce;
output  [31:0] grp_fu_1492_p_din0;
output  [31:0] grp_fu_1492_p_din1;
output  [1:0] grp_fu_1492_p_opcode;
input  [31:0] grp_fu_1492_p_dout0;
output   grp_fu_1492_p_ce;
output  [31:0] grp_fu_1496_p_din0;
output  [31:0] grp_fu_1496_p_din1;
output  [1:0] grp_fu_1496_p_opcode;
input  [31:0] grp_fu_1496_p_dout0;
output   grp_fu_1496_p_ce;
output  [31:0] grp_fu_1500_p_din0;
output  [31:0] grp_fu_1500_p_din1;
output  [1:0] grp_fu_1500_p_opcode;
input  [31:0] grp_fu_1500_p_dout0;
output   grp_fu_1500_p_ce;
output  [31:0] grp_fu_1504_p_din0;
output  [31:0] grp_fu_1504_p_din1;
output  [1:0] grp_fu_1504_p_opcode;
input  [31:0] grp_fu_1504_p_dout0;
output   grp_fu_1504_p_ce;
output  [31:0] grp_fu_1556_p_din0;
output  [31:0] grp_fu_1556_p_din1;
output  [1:0] grp_fu_1556_p_opcode;
input  [31:0] grp_fu_1556_p_dout0;
output   grp_fu_1556_p_ce;
output  [31:0] grp_fu_1560_p_din0;
output  [31:0] grp_fu_1560_p_din1;
output  [1:0] grp_fu_1560_p_opcode;
input  [31:0] grp_fu_1560_p_dout0;
output   grp_fu_1560_p_ce;
output  [31:0] grp_fu_1564_p_din0;
output  [31:0] grp_fu_1564_p_din1;
output  [1:0] grp_fu_1564_p_opcode;
input  [31:0] grp_fu_1564_p_dout0;
output   grp_fu_1564_p_ce;
output  [31:0] grp_fu_1568_p_din0;
output  [31:0] grp_fu_1568_p_din1;
output  [1:0] grp_fu_1568_p_opcode;
input  [31:0] grp_fu_1568_p_dout0;
output   grp_fu_1568_p_ce;
output  [31:0] grp_fu_1572_p_din0;
output  [31:0] grp_fu_1572_p_din1;
output  [1:0] grp_fu_1572_p_opcode;
input  [31:0] grp_fu_1572_p_dout0;
output   grp_fu_1572_p_ce;
output  [31:0] grp_fu_1576_p_din0;
output  [31:0] grp_fu_1576_p_din1;
output  [1:0] grp_fu_1576_p_opcode;
input  [31:0] grp_fu_1576_p_dout0;
output   grp_fu_1576_p_ce;
output  [31:0] grp_fu_1580_p_din0;
output  [31:0] grp_fu_1580_p_din1;
output  [1:0] grp_fu_1580_p_opcode;
input  [31:0] grp_fu_1580_p_dout0;
output   grp_fu_1580_p_ce;
output  [31:0] grp_fu_1508_p_din0;
output  [31:0] grp_fu_1508_p_din1;
input  [31:0] grp_fu_1508_p_dout0;
output   grp_fu_1508_p_ce;
output  [31:0] grp_fu_1512_p_din0;
output  [31:0] grp_fu_1512_p_din1;
input  [31:0] grp_fu_1512_p_dout0;
output   grp_fu_1512_p_ce;
output  [31:0] grp_fu_1516_p_din0;
output  [31:0] grp_fu_1516_p_din1;
input  [31:0] grp_fu_1516_p_dout0;
output   grp_fu_1516_p_ce;
output  [31:0] grp_fu_1520_p_din0;
output  [31:0] grp_fu_1520_p_din1;
input  [31:0] grp_fu_1520_p_dout0;
output   grp_fu_1520_p_ce;
output  [31:0] grp_fu_1524_p_din0;
output  [31:0] grp_fu_1524_p_din1;
input  [31:0] grp_fu_1524_p_dout0;
output   grp_fu_1524_p_ce;
output  [31:0] grp_fu_1528_p_din0;
output  [31:0] grp_fu_1528_p_din1;
input  [31:0] grp_fu_1528_p_dout0;
output   grp_fu_1528_p_ce;
output  [31:0] grp_fu_1532_p_din0;
output  [31:0] grp_fu_1532_p_din1;
input  [31:0] grp_fu_1532_p_dout0;
output   grp_fu_1532_p_ce;
output  [31:0] grp_fu_1536_p_din0;
output  [31:0] grp_fu_1536_p_din1;
input  [31:0] grp_fu_1536_p_dout0;
output   grp_fu_1536_p_ce;
output  [31:0] grp_fu_1540_p_din0;
output  [31:0] grp_fu_1540_p_din1;
input  [31:0] grp_fu_1540_p_dout0;
output   grp_fu_1540_p_ce;
output  [31:0] grp_fu_1584_p_din0;
output  [31:0] grp_fu_1584_p_din1;
input  [31:0] grp_fu_1584_p_dout0;
output   grp_fu_1584_p_ce;
output  [31:0] grp_fu_1588_p_din0;
output  [31:0] grp_fu_1588_p_din1;
input  [31:0] grp_fu_1588_p_dout0;
output   grp_fu_1588_p_ce;
output  [31:0] grp_fu_1592_p_din0;
output  [31:0] grp_fu_1592_p_din1;
input  [31:0] grp_fu_1592_p_dout0;
output   grp_fu_1592_p_ce;
output  [31:0] grp_fu_1596_p_din0;
output  [31:0] grp_fu_1596_p_din1;
input  [31:0] grp_fu_1596_p_dout0;
output   grp_fu_1596_p_ce;
output  [31:0] grp_fu_1600_p_din0;
output  [31:0] grp_fu_1600_p_din1;
input  [31:0] grp_fu_1600_p_dout0;
output   grp_fu_1600_p_ce;
output  [31:0] grp_fu_1604_p_din0;
output  [31:0] grp_fu_1604_p_din1;
input  [31:0] grp_fu_1604_p_dout0;
output   grp_fu_1604_p_ce;
output  [31:0] grp_fu_1608_p_din0;
output  [31:0] grp_fu_1608_p_din1;
input  [31:0] grp_fu_1608_p_dout0;
output   grp_fu_1608_p_ce;
output  [31:0] grp_fu_1544_p_din0;
output  [31:0] grp_fu_1544_p_din1;
output  [4:0] grp_fu_1544_p_opcode;
input  [0:0] grp_fu_1544_p_dout0;
output   grp_fu_1544_p_ce;

reg ap_idle;
reg fc2_output_ce0;
reg fc2_output_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_enable_reg_pp0_iter40;
reg    ap_enable_reg_pp0_iter41;
reg    ap_enable_reg_pp0_iter42;
reg    ap_enable_reg_pp0_iter43;
reg    ap_enable_reg_pp0_iter44;
reg    ap_enable_reg_pp0_iter45;
reg    ap_enable_reg_pp0_iter46;
reg    ap_enable_reg_pp0_iter47;
reg    ap_enable_reg_pp0_iter48;
reg    ap_enable_reg_pp0_iter49;
reg    ap_enable_reg_pp0_iter50;
reg    ap_enable_reg_pp0_iter51;
reg    ap_enable_reg_pp0_iter52;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_state29_pp0_stage0_iter28;
wire    ap_block_state30_pp0_stage0_iter29;
wire    ap_block_state31_pp0_stage0_iter30;
wire    ap_block_state32_pp0_stage0_iter31;
wire    ap_block_state33_pp0_stage0_iter32;
wire    ap_block_state34_pp0_stage0_iter33;
wire    ap_block_state35_pp0_stage0_iter34;
wire    ap_block_state36_pp0_stage0_iter35;
wire    ap_block_state37_pp0_stage0_iter36;
wire    ap_block_state38_pp0_stage0_iter37;
wire    ap_block_state39_pp0_stage0_iter38;
wire    ap_block_state40_pp0_stage0_iter39;
wire    ap_block_state41_pp0_stage0_iter40;
wire    ap_block_state42_pp0_stage0_iter41;
wire    ap_block_state43_pp0_stage0_iter42;
wire    ap_block_state44_pp0_stage0_iter43;
wire    ap_block_state45_pp0_stage0_iter44;
wire    ap_block_state46_pp0_stage0_iter45;
wire    ap_block_state47_pp0_stage0_iter46;
wire    ap_block_state48_pp0_stage0_iter47;
wire    ap_block_state49_pp0_stage0_iter48;
wire    ap_block_state50_pp0_stage0_iter49;
wire    ap_block_state51_pp0_stage0_iter50;
wire    ap_block_state52_pp0_stage0_iter51;
wire    ap_block_state53_pp0_stage0_iter52;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln135_fu_585_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] fc2_weight_0_address0;
reg    fc2_weight_0_ce0;
wire   [31:0] fc2_weight_0_q0;
wire   [3:0] fc2_weight_1_address0;
reg    fc2_weight_1_ce0;
wire   [31:0] fc2_weight_1_q0;
wire   [3:0] fc2_weight_2_address0;
reg    fc2_weight_2_ce0;
wire   [31:0] fc2_weight_2_q0;
wire   [3:0] fc2_weight_3_address0;
reg    fc2_weight_3_ce0;
wire   [31:0] fc2_weight_3_q0;
wire   [3:0] fc2_weight_4_address0;
reg    fc2_weight_4_ce0;
wire   [31:0] fc2_weight_4_q0;
wire   [3:0] fc2_weight_5_address0;
reg    fc2_weight_5_ce0;
wire   [31:0] fc2_weight_5_q0;
wire   [3:0] fc2_weight_6_address0;
reg    fc2_weight_6_ce0;
wire   [31:0] fc2_weight_6_q0;
wire   [3:0] fc2_weight_7_address0;
reg    fc2_weight_7_ce0;
wire   [31:0] fc2_weight_7_q0;
wire   [3:0] fc2_weight_8_address0;
reg    fc2_weight_8_ce0;
wire   [31:0] fc2_weight_8_q0;
wire   [3:0] fc2_weight_9_address0;
reg    fc2_weight_9_ce0;
wire   [31:0] fc2_weight_9_q0;
wire   [3:0] fc2_weight_10_address0;
reg    fc2_weight_10_ce0;
wire   [31:0] fc2_weight_10_q0;
wire   [3:0] fc2_weight_11_address0;
reg    fc2_weight_11_ce0;
wire   [31:0] fc2_weight_11_q0;
wire   [3:0] fc2_weight_12_address0;
reg    fc2_weight_12_ce0;
wire   [31:0] fc2_weight_12_q0;
wire   [3:0] fc2_weight_13_address0;
reg    fc2_weight_13_ce0;
wire   [31:0] fc2_weight_13_q0;
wire   [3:0] fc2_weight_14_address0;
reg    fc2_weight_14_ce0;
wire   [31:0] fc2_weight_14_q0;
wire   [3:0] fc2_weight_15_address0;
reg    fc2_weight_15_ce0;
wire   [31:0] fc2_weight_15_q0;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] i_4_cast_fu_597_p1;
reg   [63:0] i_4_cast_reg_747;
reg   [63:0] i_4_cast_reg_747_pp0_iter1_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter2_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter3_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter4_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter5_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter6_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter7_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter8_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter9_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter10_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter11_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter12_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter13_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter14_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter15_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter16_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter17_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter18_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter19_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter20_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter21_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter22_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter23_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter24_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter25_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter26_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter27_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter28_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter29_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter30_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter31_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter32_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter33_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter34_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter35_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter36_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter37_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter38_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter39_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter40_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter41_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter42_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter43_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter44_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter45_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter46_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter47_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter48_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter49_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter50_reg;
reg   [63:0] i_4_cast_reg_747_pp0_iter51_reg;
reg   [31:0] mul1_reg_777;
reg   [31:0] sum_9_reg_792;
reg   [31:0] mul1_1_reg_797;
reg   [31:0] sum_9_1_reg_812;
reg   [31:0] mul1_2_reg_817;
reg   [31:0] sum_9_2_reg_832;
reg   [31:0] mul1_3_reg_837;
reg   [31:0] sum_9_3_reg_852;
reg   [31:0] mul1_4_reg_857;
reg   [31:0] sum_9_4_reg_872;
reg   [31:0] mul1_5_reg_877;
reg   [31:0] sum_9_5_reg_892;
reg   [31:0] mul1_6_reg_897;
reg   [31:0] sum_9_6_reg_912;
reg   [31:0] mul1_7_reg_917;
reg   [31:0] sum_9_7_reg_932;
reg   [31:0] mul1_8_reg_937;
reg   [31:0] sum_9_8_reg_952;
reg   [31:0] mul1_9_reg_957;
reg   [31:0] sum_9_9_reg_972;
reg   [31:0] mul1_s_reg_977;
reg   [31:0] sum_9_s_reg_992;
reg   [31:0] mul1_10_reg_997;
reg   [31:0] sum_9_10_reg_1012;
reg   [31:0] mul1_11_reg_1017;
reg   [31:0] sum_9_11_reg_1032;
reg   [31:0] mul1_12_reg_1037;
reg   [31:0] sum_9_12_reg_1052;
reg   [31:0] mul1_13_reg_1057;
reg   [31:0] sum_9_13_reg_1072;
reg   [31:0] mul1_14_reg_1077;
reg   [31:0] sum_9_14_reg_1082;
reg   [31:0] sum_9_14_reg_1082_pp0_iter51_reg;
wire    ap_block_pp0_stage0;
reg   [3:0] i_4_fu_106;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i;
wire   [3:0] add_ln135_fu_591_p2;
wire   [31:0] bitcast_ln7_fu_607_p1;
wire   [7:0] tmp_s_fu_610_p4;
wire   [22:0] trunc_ln7_fu_620_p1;
wire   [0:0] icmp_ln7_2_fu_630_p2;
wire   [0:0] icmp_ln7_fu_624_p2;
wire   [0:0] or_ln7_fu_636_p2;
wire   [0:0] and_ln7_fu_642_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg    ap_loop_exit_ready_pp0_iter39_reg;
reg    ap_loop_exit_ready_pp0_iter40_reg;
reg    ap_loop_exit_ready_pp0_iter41_reg;
reg    ap_loop_exit_ready_pp0_iter42_reg;
reg    ap_loop_exit_ready_pp0_iter43_reg;
reg    ap_loop_exit_ready_pp0_iter44_reg;
reg    ap_loop_exit_ready_pp0_iter45_reg;
reg    ap_loop_exit_ready_pp0_iter46_reg;
reg    ap_loop_exit_ready_pp0_iter47_reg;
reg    ap_loop_exit_ready_pp0_iter48_reg;
reg    ap_loop_exit_ready_pp0_iter49_reg;
reg    ap_loop_exit_ready_pp0_iter50_reg;
reg    ap_loop_exit_ready_pp0_iter51_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter40 = 1'b0;
#0 ap_enable_reg_pp0_iter41 = 1'b0;
#0 ap_enable_reg_pp0_iter42 = 1'b0;
#0 ap_enable_reg_pp0_iter43 = 1'b0;
#0 ap_enable_reg_pp0_iter44 = 1'b0;
#0 ap_enable_reg_pp0_iter45 = 1'b0;
#0 ap_enable_reg_pp0_iter46 = 1'b0;
#0 ap_enable_reg_pp0_iter47 = 1'b0;
#0 ap_enable_reg_pp0_iter48 = 1'b0;
#0 ap_enable_reg_pp0_iter49 = 1'b0;
#0 ap_enable_reg_pp0_iter50 = 1'b0;
#0 ap_enable_reg_pp0_iter51 = 1'b0;
#0 ap_enable_reg_pp0_iter52 = 1'b0;
#0 ap_done_reg = 1'b0;
end

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_0 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_0_address0),
    .ce0(fc2_weight_0_ce0),
    .q0(fc2_weight_0_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_1 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_1_address0),
    .ce0(fc2_weight_1_ce0),
    .q0(fc2_weight_1_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_2 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_2_address0),
    .ce0(fc2_weight_2_ce0),
    .q0(fc2_weight_2_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_3 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_3_address0),
    .ce0(fc2_weight_3_ce0),
    .q0(fc2_weight_3_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_4 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_4_address0),
    .ce0(fc2_weight_4_ce0),
    .q0(fc2_weight_4_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_5 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_5_address0),
    .ce0(fc2_weight_5_ce0),
    .q0(fc2_weight_5_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_6 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_6_address0),
    .ce0(fc2_weight_6_ce0),
    .q0(fc2_weight_6_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_7 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_7_address0),
    .ce0(fc2_weight_7_ce0),
    .q0(fc2_weight_7_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_8 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_8_address0),
    .ce0(fc2_weight_8_ce0),
    .q0(fc2_weight_8_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_9 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_9_address0),
    .ce0(fc2_weight_9_ce0),
    .q0(fc2_weight_9_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_10 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_10_address0),
    .ce0(fc2_weight_10_ce0),
    .q0(fc2_weight_10_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_11 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_11_address0),
    .ce0(fc2_weight_11_ce0),
    .q0(fc2_weight_11_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_12 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_12_address0),
    .ce0(fc2_weight_12_ce0),
    .q0(fc2_weight_12_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_13 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_13_address0),
    .ce0(fc2_weight_13_ce0),
    .q0(fc2_weight_13_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_14 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_14_address0),
    .ce0(fc2_weight_14_ce0),
    .q0(fc2_weight_14_q0)
);

DNN_DNN_Pipeline_VITIS_LOOP_135_6_fc2_weight_15 #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
fc2_weight_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_15_address0),
    .ce0(fc2_weight_15_ce0),
    .q0(fc2_weight_15_q0)
);

DNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter51_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter40 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter41 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter42 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter42 <= ap_enable_reg_pp0_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter43 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter43 <= ap_enable_reg_pp0_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter44 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter44 <= ap_enable_reg_pp0_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter45 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter45 <= ap_enable_reg_pp0_iter44;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter46 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter46 <= ap_enable_reg_pp0_iter45;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter47 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter47 <= ap_enable_reg_pp0_iter46;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter48 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter48 <= ap_enable_reg_pp0_iter47;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter49 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter49 <= ap_enable_reg_pp0_iter48;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter50 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter50 <= ap_enable_reg_pp0_iter49;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter51 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter51 <= ap_enable_reg_pp0_iter50;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter52 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter52 <= ap_enable_reg_pp0_iter51;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln135_fu_585_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_4_fu_106 <= add_ln135_fu_591_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_4_fu_106 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
        ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
        ap_loop_exit_ready_pp0_iter41_reg <= ap_loop_exit_ready_pp0_iter40_reg;
        ap_loop_exit_ready_pp0_iter42_reg <= ap_loop_exit_ready_pp0_iter41_reg;
        ap_loop_exit_ready_pp0_iter43_reg <= ap_loop_exit_ready_pp0_iter42_reg;
        ap_loop_exit_ready_pp0_iter44_reg <= ap_loop_exit_ready_pp0_iter43_reg;
        ap_loop_exit_ready_pp0_iter45_reg <= ap_loop_exit_ready_pp0_iter44_reg;
        ap_loop_exit_ready_pp0_iter46_reg <= ap_loop_exit_ready_pp0_iter45_reg;
        ap_loop_exit_ready_pp0_iter47_reg <= ap_loop_exit_ready_pp0_iter46_reg;
        ap_loop_exit_ready_pp0_iter48_reg <= ap_loop_exit_ready_pp0_iter47_reg;
        ap_loop_exit_ready_pp0_iter49_reg <= ap_loop_exit_ready_pp0_iter48_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter50_reg <= ap_loop_exit_ready_pp0_iter49_reg;
        ap_loop_exit_ready_pp0_iter51_reg <= ap_loop_exit_ready_pp0_iter50_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        i_4_cast_reg_747_pp0_iter10_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter9_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter11_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter10_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter12_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter11_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter13_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter12_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter14_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter13_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter15_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter14_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter16_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter15_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter17_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter16_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter18_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter17_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter19_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter18_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter20_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter19_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter21_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter20_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter22_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter21_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter23_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter22_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter24_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter23_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter25_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter24_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter26_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter25_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter27_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter26_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter28_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter27_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter29_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter28_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter2_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter1_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter30_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter29_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter31_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter30_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter32_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter31_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter33_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter32_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter34_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter33_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter35_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter34_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter36_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter35_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter37_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter36_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter38_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter37_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter39_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter38_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter3_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter2_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter40_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter39_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter41_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter40_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter42_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter41_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter43_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter42_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter44_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter43_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter45_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter44_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter46_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter45_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter47_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter46_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter48_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter47_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter49_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter48_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter4_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter3_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter50_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter49_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter51_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter50_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter5_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter4_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter6_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter5_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter7_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter6_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter8_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter7_reg[3 : 0];
        i_4_cast_reg_747_pp0_iter9_reg[3 : 0] <= i_4_cast_reg_747_pp0_iter8_reg[3 : 0];
        mul1_10_reg_997 <= grp_fu_1592_p_dout0;
        mul1_11_reg_1017 <= grp_fu_1596_p_dout0;
        mul1_12_reg_1037 <= grp_fu_1600_p_dout0;
        mul1_13_reg_1057 <= grp_fu_1604_p_dout0;
        mul1_14_reg_1077 <= grp_fu_1608_p_dout0;
        mul1_1_reg_797 <= grp_fu_1512_p_dout0;
        mul1_2_reg_817 <= grp_fu_1516_p_dout0;
        mul1_3_reg_837 <= grp_fu_1520_p_dout0;
        mul1_4_reg_857 <= grp_fu_1524_p_dout0;
        mul1_5_reg_877 <= grp_fu_1528_p_dout0;
        mul1_6_reg_897 <= grp_fu_1532_p_dout0;
        mul1_7_reg_917 <= grp_fu_1536_p_dout0;
        mul1_8_reg_937 <= grp_fu_1540_p_dout0;
        mul1_9_reg_957 <= grp_fu_1584_p_dout0;
        mul1_reg_777 <= grp_fu_1508_p_dout0;
        mul1_s_reg_977 <= grp_fu_1588_p_dout0;
        sum_9_10_reg_1012 <= grp_fu_1564_p_dout0;
        sum_9_11_reg_1032 <= grp_fu_1568_p_dout0;
        sum_9_12_reg_1052 <= grp_fu_1572_p_dout0;
        sum_9_13_reg_1072 <= grp_fu_1576_p_dout0;
        sum_9_14_reg_1082 <= grp_fu_1580_p_dout0;
        sum_9_14_reg_1082_pp0_iter51_reg <= sum_9_14_reg_1082;
        sum_9_1_reg_812 <= grp_fu_1476_p_dout0;
        sum_9_2_reg_832 <= grp_fu_1480_p_dout0;
        sum_9_3_reg_852 <= grp_fu_1484_p_dout0;
        sum_9_4_reg_872 <= grp_fu_1488_p_dout0;
        sum_9_5_reg_892 <= grp_fu_1492_p_dout0;
        sum_9_6_reg_912 <= grp_fu_1496_p_dout0;
        sum_9_7_reg_932 <= grp_fu_1500_p_dout0;
        sum_9_8_reg_952 <= grp_fu_1504_p_dout0;
        sum_9_9_reg_972 <= grp_fu_1556_p_dout0;
        sum_9_reg_792 <= grp_fu_1472_p_dout0;
        sum_9_s_reg_992 <= grp_fu_1560_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_4_cast_reg_747_pp0_iter1_reg[3 : 0] <= i_4_cast_reg_747[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln135_fu_585_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_4_cast_reg_747[3 : 0] <= i_4_cast_fu_597_p1[3 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln135_fu_585_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter51_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter52 == 1'b0) & (ap_enable_reg_pp0_iter51 == 1'b0) & (ap_enable_reg_pp0_iter50 == 1'b0) & (ap_enable_reg_pp0_iter49 == 1'b0) & (ap_enable_reg_pp0_iter48 == 1'b0) & (ap_enable_reg_pp0_iter47 == 1'b0) & (ap_enable_reg_pp0_iter46 == 1'b0) & (ap_enable_reg_pp0_iter45 == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b0) & (ap_enable_reg_pp0_iter43 == 1'b0) & (ap_enable_reg_pp0_iter42 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 4'd0;
    end else begin
        ap_sig_allocacmp_i = i_4_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter52 == 1'b1))) begin
        fc2_output_ce0 = 1'b1;
    end else begin
        fc2_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter52 == 1'b1))) begin
        fc2_output_we0 = 1'b1;
    end else begin
        fc2_output_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fc2_weight_0_ce0 = 1'b1;
    end else begin
        fc2_weight_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter30 == 1'b1))) begin
        fc2_weight_10_ce0 = 1'b1;
    end else begin
        fc2_weight_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter33 == 1'b1))) begin
        fc2_weight_11_ce0 = 1'b1;
    end else begin
        fc2_weight_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter36 == 1'b1))) begin
        fc2_weight_12_ce0 = 1'b1;
    end else begin
        fc2_weight_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1))) begin
        fc2_weight_13_ce0 = 1'b1;
    end else begin
        fc2_weight_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter42 == 1'b1))) begin
        fc2_weight_14_ce0 = 1'b1;
    end else begin
        fc2_weight_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter45 == 1'b1))) begin
        fc2_weight_15_ce0 = 1'b1;
    end else begin
        fc2_weight_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fc2_weight_1_ce0 = 1'b1;
    end else begin
        fc2_weight_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fc2_weight_2_ce0 = 1'b1;
    end else begin
        fc2_weight_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fc2_weight_3_ce0 = 1'b1;
    end else begin
        fc2_weight_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fc2_weight_4_ce0 = 1'b1;
    end else begin
        fc2_weight_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fc2_weight_5_ce0 = 1'b1;
    end else begin
        fc2_weight_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fc2_weight_6_ce0 = 1'b1;
    end else begin
        fc2_weight_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fc2_weight_7_ce0 = 1'b1;
    end else begin
        fc2_weight_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        fc2_weight_8_ce0 = 1'b1;
    end else begin
        fc2_weight_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        fc2_weight_9_ce0 = 1'b1;
    end else begin
        fc2_weight_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln135_fu_591_p2 = (ap_sig_allocacmp_i + 4'd1);

assign and_ln7_fu_642_p2 = (or_ln7_fu_636_p2 & grp_fu_1544_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter35 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter36 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage0_iter37 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage0_iter38 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage0_iter39 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter40 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage0_iter41 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage0_iter42 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage0_iter43 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage0_iter44 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage0_iter45 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage0_iter46 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage0_iter47 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage0_iter48 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp0_stage0_iter49 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp0_stage0_iter50 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp0_stage0_iter51 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp0_stage0_iter52 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln7_fu_607_p1 = sum_9_14_reg_1082_pp0_iter51_reg;

assign fc2_output_address0 = i_4_cast_reg_747_pp0_iter51_reg;

assign fc2_output_d0 = ((and_ln7_fu_642_p2[0:0] == 1'b1) ? 32'd0 : sum_9_14_reg_1082_pp0_iter51_reg);

assign fc2_weight_0_address0 = i_4_cast_fu_597_p1;

assign fc2_weight_10_address0 = i_4_cast_reg_747_pp0_iter29_reg;

assign fc2_weight_11_address0 = i_4_cast_reg_747_pp0_iter32_reg;

assign fc2_weight_12_address0 = i_4_cast_reg_747_pp0_iter35_reg;

assign fc2_weight_13_address0 = i_4_cast_reg_747_pp0_iter38_reg;

assign fc2_weight_14_address0 = i_4_cast_reg_747_pp0_iter41_reg;

assign fc2_weight_15_address0 = i_4_cast_reg_747_pp0_iter44_reg;

assign fc2_weight_1_address0 = i_4_cast_reg_747_pp0_iter2_reg;

assign fc2_weight_2_address0 = i_4_cast_reg_747_pp0_iter5_reg;

assign fc2_weight_3_address0 = i_4_cast_reg_747_pp0_iter8_reg;

assign fc2_weight_4_address0 = i_4_cast_reg_747_pp0_iter11_reg;

assign fc2_weight_5_address0 = i_4_cast_reg_747_pp0_iter14_reg;

assign fc2_weight_6_address0 = i_4_cast_reg_747_pp0_iter17_reg;

assign fc2_weight_7_address0 = i_4_cast_reg_747_pp0_iter20_reg;

assign fc2_weight_8_address0 = i_4_cast_reg_747_pp0_iter23_reg;

assign fc2_weight_9_address0 = i_4_cast_reg_747_pp0_iter26_reg;

assign grp_fu_1472_p_ce = 1'b1;

assign grp_fu_1472_p_din0 = mul1_reg_777;

assign grp_fu_1472_p_din1 = 32'd0;

assign grp_fu_1472_p_opcode = 2'd0;

assign grp_fu_1476_p_ce = 1'b1;

assign grp_fu_1476_p_din0 = sum_9_reg_792;

assign grp_fu_1476_p_din1 = mul1_1_reg_797;

assign grp_fu_1476_p_opcode = 2'd0;

assign grp_fu_1480_p_ce = 1'b1;

assign grp_fu_1480_p_din0 = sum_9_1_reg_812;

assign grp_fu_1480_p_din1 = mul1_2_reg_817;

assign grp_fu_1480_p_opcode = 2'd0;

assign grp_fu_1484_p_ce = 1'b1;

assign grp_fu_1484_p_din0 = sum_9_2_reg_832;

assign grp_fu_1484_p_din1 = mul1_3_reg_837;

assign grp_fu_1484_p_opcode = 2'd0;

assign grp_fu_1488_p_ce = 1'b1;

assign grp_fu_1488_p_din0 = sum_9_3_reg_852;

assign grp_fu_1488_p_din1 = mul1_4_reg_857;

assign grp_fu_1488_p_opcode = 2'd0;

assign grp_fu_1492_p_ce = 1'b1;

assign grp_fu_1492_p_din0 = sum_9_4_reg_872;

assign grp_fu_1492_p_din1 = mul1_5_reg_877;

assign grp_fu_1492_p_opcode = 2'd0;

assign grp_fu_1496_p_ce = 1'b1;

assign grp_fu_1496_p_din0 = sum_9_5_reg_892;

assign grp_fu_1496_p_din1 = mul1_6_reg_897;

assign grp_fu_1496_p_opcode = 2'd0;

assign grp_fu_1500_p_ce = 1'b1;

assign grp_fu_1500_p_din0 = sum_9_6_reg_912;

assign grp_fu_1500_p_din1 = mul1_7_reg_917;

assign grp_fu_1500_p_opcode = 2'd0;

assign grp_fu_1504_p_ce = 1'b1;

assign grp_fu_1504_p_din0 = sum_9_7_reg_932;

assign grp_fu_1504_p_din1 = mul1_8_reg_937;

assign grp_fu_1504_p_opcode = 2'd0;

assign grp_fu_1508_p_ce = 1'b1;

assign grp_fu_1508_p_din0 = fc1_output_load;

assign grp_fu_1508_p_din1 = fc2_weight_0_q0;

assign grp_fu_1512_p_ce = 1'b1;

assign grp_fu_1512_p_din0 = fc1_output_load_1;

assign grp_fu_1512_p_din1 = fc2_weight_1_q0;

assign grp_fu_1516_p_ce = 1'b1;

assign grp_fu_1516_p_din0 = fc1_output_load_2;

assign grp_fu_1516_p_din1 = fc2_weight_2_q0;

assign grp_fu_1520_p_ce = 1'b1;

assign grp_fu_1520_p_din0 = fc1_output_load_3;

assign grp_fu_1520_p_din1 = fc2_weight_3_q0;

assign grp_fu_1524_p_ce = 1'b1;

assign grp_fu_1524_p_din0 = fc1_output_load_4;

assign grp_fu_1524_p_din1 = fc2_weight_4_q0;

assign grp_fu_1528_p_ce = 1'b1;

assign grp_fu_1528_p_din0 = fc1_output_load_5;

assign grp_fu_1528_p_din1 = fc2_weight_5_q0;

assign grp_fu_1532_p_ce = 1'b1;

assign grp_fu_1532_p_din0 = fc1_output_load_6;

assign grp_fu_1532_p_din1 = fc2_weight_6_q0;

assign grp_fu_1536_p_ce = 1'b1;

assign grp_fu_1536_p_din0 = fc1_output_load_7;

assign grp_fu_1536_p_din1 = fc2_weight_7_q0;

assign grp_fu_1540_p_ce = 1'b1;

assign grp_fu_1540_p_din0 = fc1_output_load_8;

assign grp_fu_1540_p_din1 = fc2_weight_8_q0;

assign grp_fu_1544_p_ce = 1'b1;

assign grp_fu_1544_p_din0 = sum_9_14_reg_1082;

assign grp_fu_1544_p_din1 = 32'd0;

assign grp_fu_1544_p_opcode = 5'd4;

assign grp_fu_1556_p_ce = 1'b1;

assign grp_fu_1556_p_din0 = sum_9_8_reg_952;

assign grp_fu_1556_p_din1 = mul1_9_reg_957;

assign grp_fu_1556_p_opcode = 2'd0;

assign grp_fu_1560_p_ce = 1'b1;

assign grp_fu_1560_p_din0 = sum_9_9_reg_972;

assign grp_fu_1560_p_din1 = mul1_s_reg_977;

assign grp_fu_1560_p_opcode = 2'd0;

assign grp_fu_1564_p_ce = 1'b1;

assign grp_fu_1564_p_din0 = sum_9_s_reg_992;

assign grp_fu_1564_p_din1 = mul1_10_reg_997;

assign grp_fu_1564_p_opcode = 2'd0;

assign grp_fu_1568_p_ce = 1'b1;

assign grp_fu_1568_p_din0 = sum_9_10_reg_1012;

assign grp_fu_1568_p_din1 = mul1_11_reg_1017;

assign grp_fu_1568_p_opcode = 2'd0;

assign grp_fu_1572_p_ce = 1'b1;

assign grp_fu_1572_p_din0 = sum_9_11_reg_1032;

assign grp_fu_1572_p_din1 = mul1_12_reg_1037;

assign grp_fu_1572_p_opcode = 2'd0;

assign grp_fu_1576_p_ce = 1'b1;

assign grp_fu_1576_p_din0 = sum_9_12_reg_1052;

assign grp_fu_1576_p_din1 = mul1_13_reg_1057;

assign grp_fu_1576_p_opcode = 2'd0;

assign grp_fu_1580_p_ce = 1'b1;

assign grp_fu_1580_p_din0 = sum_9_13_reg_1072;

assign grp_fu_1580_p_din1 = mul1_14_reg_1077;

assign grp_fu_1580_p_opcode = 2'd0;

assign grp_fu_1584_p_ce = 1'b1;

assign grp_fu_1584_p_din0 = fc1_output_load_9;

assign grp_fu_1584_p_din1 = fc2_weight_9_q0;

assign grp_fu_1588_p_ce = 1'b1;

assign grp_fu_1588_p_din0 = fc1_output_load_10;

assign grp_fu_1588_p_din1 = fc2_weight_10_q0;

assign grp_fu_1592_p_ce = 1'b1;

assign grp_fu_1592_p_din0 = fc1_output_load_11;

assign grp_fu_1592_p_din1 = fc2_weight_11_q0;

assign grp_fu_1596_p_ce = 1'b1;

assign grp_fu_1596_p_din0 = fc1_output_load_12;

assign grp_fu_1596_p_din1 = fc2_weight_12_q0;

assign grp_fu_1600_p_ce = 1'b1;

assign grp_fu_1600_p_din0 = fc1_output_load_13;

assign grp_fu_1600_p_din1 = fc2_weight_13_q0;

assign grp_fu_1604_p_ce = 1'b1;

assign grp_fu_1604_p_din0 = fc1_output_load_14;

assign grp_fu_1604_p_din1 = fc2_weight_14_q0;

assign grp_fu_1608_p_ce = 1'b1;

assign grp_fu_1608_p_din0 = fc1_output_load_15;

assign grp_fu_1608_p_din1 = fc2_weight_15_q0;

assign i_4_cast_fu_597_p1 = ap_sig_allocacmp_i;

assign icmp_ln135_fu_585_p2 = ((ap_sig_allocacmp_i == 4'd12) ? 1'b1 : 1'b0);

assign icmp_ln7_2_fu_630_p2 = ((trunc_ln7_fu_620_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_624_p2 = ((tmp_s_fu_610_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln7_fu_636_p2 = (icmp_ln7_fu_624_p2 | icmp_ln7_2_fu_630_p2);

assign tmp_s_fu_610_p4 = {{bitcast_ln7_fu_607_p1[30:23]}};

assign trunc_ln7_fu_620_p1 = bitcast_ln7_fu_607_p1[22:0];

always @ (posedge ap_clk) begin
    i_4_cast_reg_747[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter1_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter2_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter3_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter4_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter5_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter6_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter7_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter8_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter9_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter10_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter11_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter12_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter13_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter14_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter15_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter16_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter17_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter18_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter19_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter20_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter21_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter22_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter23_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter24_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter25_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter26_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter27_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter28_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter29_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter30_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter31_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter32_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter33_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter34_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter35_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter36_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter37_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter38_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter39_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter40_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter41_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter42_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter43_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter44_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter45_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter46_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter47_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter48_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter49_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter50_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_747_pp0_iter51_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //DNN_DNN_Pipeline_VITIS_LOOP_135_6
