// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module DNN_DNN_Pipeline_VITIS_LOOP_60_1_VITIS_LOOP_61_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv1_output_address0,
        conv1_output_ce0,
        conv1_output_q0,
        conv1_output_address1,
        conv1_output_ce1,
        conv1_output_q1,
        conv1_output_address2,
        conv1_output_ce2,
        conv1_output_q2,
        conv1_output_address3,
        conv1_output_ce3,
        conv1_output_q3,
        conv1_output_address4,
        conv1_output_ce4,
        conv1_output_q4,
        conv1_output_address5,
        conv1_output_ce5,
        conv1_output_q5,
        conv1_output_address6,
        conv1_output_ce6,
        conv1_output_q6,
        pool1_output_address0,
        pool1_output_ce0,
        pool1_output_we0,
        pool1_output_d0,
        grp_fu_1544_p_din0,
        grp_fu_1544_p_din1,
        grp_fu_1544_p_opcode,
        grp_fu_1544_p_dout0,
        grp_fu_1544_p_ce,
        grp_fu_1548_p_din0,
        grp_fu_1548_p_din1,
        grp_fu_1548_p_opcode,
        grp_fu_1548_p_dout0,
        grp_fu_1548_p_ce,
        grp_fu_1552_p_din0,
        grp_fu_1552_p_din1,
        grp_fu_1552_p_opcode,
        grp_fu_1552_p_dout0,
        grp_fu_1552_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] conv1_output_address0;
output   conv1_output_ce0;
input  [31:0] conv1_output_q0;
output  [5:0] conv1_output_address1;
output   conv1_output_ce1;
input  [31:0] conv1_output_q1;
output  [5:0] conv1_output_address2;
output   conv1_output_ce2;
input  [31:0] conv1_output_q2;
output  [5:0] conv1_output_address3;
output   conv1_output_ce3;
input  [31:0] conv1_output_q3;
output  [5:0] conv1_output_address4;
output   conv1_output_ce4;
input  [31:0] conv1_output_q4;
output  [5:0] conv1_output_address5;
output   conv1_output_ce5;
input  [31:0] conv1_output_q5;
output  [5:0] conv1_output_address6;
output   conv1_output_ce6;
input  [31:0] conv1_output_q6;
output  [3:0] pool1_output_address0;
output   pool1_output_ce0;
output   pool1_output_we0;
output  [31:0] pool1_output_d0;
output  [31:0] grp_fu_1544_p_din0;
output  [31:0] grp_fu_1544_p_din1;
output  [4:0] grp_fu_1544_p_opcode;
input  [0:0] grp_fu_1544_p_dout0;
output   grp_fu_1544_p_ce;
output  [31:0] grp_fu_1548_p_din0;
output  [31:0] grp_fu_1548_p_din1;
output  [4:0] grp_fu_1548_p_opcode;
input  [0:0] grp_fu_1548_p_dout0;
output   grp_fu_1548_p_ce;
output  [31:0] grp_fu_1552_p_din0;
output  [31:0] grp_fu_1552_p_din1;
output  [4:0] grp_fu_1552_p_opcode;
input  [0:0] grp_fu_1552_p_dout0;
output   grp_fu_1552_p_ce;

reg ap_idle;
reg conv1_output_ce0;
reg conv1_output_ce1;
reg conv1_output_ce2;
reg conv1_output_ce3;
reg conv1_output_ce4;
reg conv1_output_ce5;
reg conv1_output_ce6;
reg pool1_output_ce0;
reg pool1_output_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln60_fu_209_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] select_ln60_fu_241_p3;
reg   [3:0] select_ln60_reg_706;
reg   [3:0] select_ln60_reg_706_pp0_iter1_reg;
wire   [5:0] tmp_43_cast_fu_261_p3;
reg   [5:0] tmp_43_cast_reg_711;
reg   [5:0] tmp_43_cast_reg_711_pp0_iter1_reg;
wire   [5:0] add_ln65_fu_302_p2;
reg   [5:0] add_ln65_reg_721;
reg   [5:0] add_ln65_reg_721_pp0_iter1_reg;
reg   [5:0] add_ln65_reg_721_pp0_iter2_reg;
reg   [5:0] add_ln65_reg_721_pp0_iter3_reg;
wire   [2:0] or_ln65_fu_313_p2;
reg   [2:0] or_ln65_reg_731;
reg   [2:0] or_ln65_reg_731_pp0_iter1_reg;
wire   [5:0] tmp_16_fu_332_p3;
reg   [5:0] tmp_16_reg_741;
reg   [5:0] tmp_16_reg_741_pp0_iter1_reg;
reg   [5:0] tmp_16_reg_741_pp0_iter2_reg;
reg   [5:0] tmp_16_reg_741_pp0_iter3_reg;
reg   [5:0] tmp_16_reg_741_pp0_iter4_reg;
reg   [5:0] tmp_16_reg_741_pp0_iter5_reg;
reg   [1:0] tmp_17_reg_751;
reg   [1:0] tmp_17_reg_751_pp0_iter1_reg;
reg   [1:0] tmp_17_reg_751_pp0_iter2_reg;
reg   [1:0] tmp_17_reg_751_pp0_iter3_reg;
reg   [1:0] tmp_17_reg_751_pp0_iter4_reg;
reg   [1:0] tmp_17_reg_751_pp0_iter5_reg;
reg   [1:0] tmp_17_reg_751_pp0_iter6_reg;
reg   [1:0] tmp_18_reg_756;
reg   [1:0] tmp_18_reg_756_pp0_iter1_reg;
reg   [1:0] tmp_18_reg_756_pp0_iter2_reg;
reg   [1:0] tmp_18_reg_756_pp0_iter3_reg;
reg   [1:0] tmp_18_reg_756_pp0_iter4_reg;
reg   [1:0] tmp_18_reg_756_pp0_iter5_reg;
reg   [1:0] tmp_18_reg_756_pp0_iter6_reg;
wire   [0:0] icmp_ln65_fu_422_p2;
reg   [0:0] icmp_ln65_reg_771;
wire   [0:0] icmp_ln65_1_fu_428_p2;
reg   [0:0] icmp_ln65_1_reg_776;
wire   [0:0] icmp_ln65_2_fu_434_p2;
reg   [0:0] icmp_ln65_2_reg_781;
wire   [0:0] icmp_ln65_3_fu_440_p2;
reg   [0:0] icmp_ln65_3_reg_786;
reg   [31:0] conv1_output_load_2_reg_791;
reg   [31:0] conv1_output_load_2_reg_791_pp0_iter2_reg;
reg   [31:0] conv1_output_load_4_reg_797;
reg   [31:0] conv1_output_load_4_reg_797_pp0_iter2_reg;
reg   [31:0] conv1_output_load_4_reg_797_pp0_iter3_reg;
reg   [31:0] conv1_output_load_4_reg_797_pp0_iter4_reg;
wire   [5:0] add_ln65_1_fu_480_p2;
reg   [5:0] add_ln65_1_reg_803;
reg   [5:0] add_ln65_1_reg_803_pp0_iter3_reg;
wire   [0:0] icmp_ln65_4_fu_525_p2;
reg   [0:0] icmp_ln65_4_reg_818;
wire   [0:0] icmp_ln65_5_fu_531_p2;
reg   [0:0] icmp_ln65_5_reg_823;
wire   [0:0] icmp_ln65_6_fu_537_p2;
reg   [0:0] icmp_ln65_6_reg_828;
wire   [0:0] icmp_ln65_7_fu_543_p2;
reg   [0:0] icmp_ln65_7_reg_833;
wire   [5:0] select_ln65_1_fu_569_p3;
reg   [5:0] select_ln65_1_reg_838;
reg   [5:0] select_ln65_1_reg_838_pp0_iter5_reg;
wire   [0:0] icmp_ln65_8_fu_615_p2;
reg   [0:0] icmp_ln65_8_reg_853;
wire   [0:0] icmp_ln65_9_fu_621_p2;
reg   [0:0] icmp_ln65_9_reg_858;
wire   [0:0] icmp_ln65_10_fu_627_p2;
reg   [0:0] icmp_ln65_10_reg_863;
wire   [0:0] icmp_ln65_11_fu_633_p2;
reg   [0:0] icmp_ln65_11_reg_868;
wire   [63:0] zext_ln62_1_fu_297_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln65_fu_308_p1;
wire   [63:0] zext_ln65_2_fu_327_p1;
wire   [63:0] zext_ln65_3_fu_340_p1;
wire   [63:0] zext_ln65_5_fu_485_p1;
wire   [63:0] zext_ln65_6_fu_575_p1;
wire   [63:0] zext_ln65_7_fu_665_p1;
wire   [63:0] zext_ln70_fu_676_p1;
reg   [3:0] j_fu_64;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_load;
wire   [3:0] add_ln61_fu_365_p2;
reg   [3:0] i_fu_68;
reg   [3:0] ap_sig_allocacmp_i_load;
wire   [3:0] select_ln60_1_fu_249_p3;
reg   [4:0] indvar_flatten24_fu_72;
reg   [4:0] ap_sig_allocacmp_indvar_flatten24_load;
wire   [4:0] add_ln60_1_fu_215_p2;
wire   [0:0] tmp_fu_233_p3;
wire   [3:0] add_ln60_fu_227_p2;
wire   [2:0] trunc_ln62_fu_257_p1;
wire   [2:0] or_ln60_fu_269_p2;
wire   [5:0] zext_ln62_fu_287_p1;
wire   [5:0] add_ln62_fu_291_p2;
wire   [5:0] tmp_14_fu_275_p3;
wire   [2:0] empty_61_fu_283_p1;
wire   [6:0] tmp_15_fu_319_p3;
wire   [31:0] bitcast_ln65_fu_386_p1;
wire   [31:0] bitcast_ln65_1_fu_404_p1;
wire   [7:0] tmp_3_fu_390_p4;
wire   [22:0] trunc_ln65_fu_400_p1;
wire   [7:0] tmp_4_fu_408_p4;
wire   [22:0] trunc_ln65_1_fu_418_p1;
wire   [0:0] or_ln65_1_fu_449_p2;
wire   [0:0] or_ln65_2_fu_453_p2;
wire   [0:0] and_ln65_fu_457_p2;
wire   [0:0] and_ln65_1_fu_463_p2;
wire   [3:0] zext_ln65_1_fu_446_p1;
wire   [3:0] select_ln65_fu_469_p3;
wire   [5:0] zext_ln65_4_fu_476_p1;
wire   [31:0] bitcast_ln65_2_fu_490_p1;
wire   [31:0] bitcast_ln65_3_fu_507_p1;
wire   [7:0] tmp_6_fu_493_p4;
wire   [22:0] trunc_ln65_2_fu_503_p1;
wire   [7:0] tmp_7_fu_511_p4;
wire   [22:0] trunc_ln65_3_fu_521_p1;
wire   [0:0] or_ln65_3_fu_549_p2;
wire   [0:0] or_ln65_4_fu_553_p2;
wire   [0:0] and_ln65_2_fu_557_p2;
wire   [0:0] and_ln65_3_fu_563_p2;
wire   [31:0] bitcast_ln65_4_fu_580_p1;
wire   [31:0] bitcast_ln65_5_fu_597_p1;
wire   [7:0] tmp_9_fu_583_p4;
wire   [22:0] trunc_ln65_4_fu_593_p1;
wire   [7:0] tmp_s_fu_601_p4;
wire   [22:0] trunc_ln65_5_fu_611_p1;
wire   [0:0] or_ln65_5_fu_639_p2;
wire   [0:0] or_ln65_6_fu_643_p2;
wire   [0:0] and_ln65_4_fu_647_p2;
wire   [0:0] and_ln65_5_fu_653_p2;
wire   [5:0] select_ln65_2_fu_659_p3;
wire   [3:0] tmp_19_fu_670_p3;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_done_reg = 1'b0;
end

DNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln60_fu_209_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_68 <= select_ln60_1_fu_249_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_68 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln60_fu_209_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten24_fu_72 <= add_ln60_1_fu_215_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten24_fu_72 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln60_fu_209_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_64 <= add_ln61_fu_365_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_64 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln65_1_reg_803 <= add_ln65_1_fu_480_p2;
        add_ln65_1_reg_803_pp0_iter3_reg <= add_ln65_1_reg_803;
        add_ln65_reg_721_pp0_iter2_reg <= add_ln65_reg_721_pp0_iter1_reg;
        add_ln65_reg_721_pp0_iter3_reg <= add_ln65_reg_721_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        conv1_output_load_2_reg_791_pp0_iter2_reg <= conv1_output_load_2_reg_791;
        conv1_output_load_4_reg_797_pp0_iter2_reg <= conv1_output_load_4_reg_797;
        conv1_output_load_4_reg_797_pp0_iter3_reg <= conv1_output_load_4_reg_797_pp0_iter2_reg;
        conv1_output_load_4_reg_797_pp0_iter4_reg <= conv1_output_load_4_reg_797_pp0_iter3_reg;
        icmp_ln65_10_reg_863 <= icmp_ln65_10_fu_627_p2;
        icmp_ln65_11_reg_868 <= icmp_ln65_11_fu_633_p2;
        icmp_ln65_4_reg_818 <= icmp_ln65_4_fu_525_p2;
        icmp_ln65_5_reg_823 <= icmp_ln65_5_fu_531_p2;
        icmp_ln65_6_reg_828 <= icmp_ln65_6_fu_537_p2;
        icmp_ln65_7_reg_833 <= icmp_ln65_7_fu_543_p2;
        icmp_ln65_8_reg_853 <= icmp_ln65_8_fu_615_p2;
        icmp_ln65_9_reg_858 <= icmp_ln65_9_fu_621_p2;
        select_ln65_1_reg_838 <= select_ln65_1_fu_569_p3;
        select_ln65_1_reg_838_pp0_iter5_reg <= select_ln65_1_reg_838;
        tmp_16_reg_741_pp0_iter2_reg[2 : 1] <= tmp_16_reg_741_pp0_iter1_reg[2 : 1];
tmp_16_reg_741_pp0_iter2_reg[5 : 4] <= tmp_16_reg_741_pp0_iter1_reg[5 : 4];
        tmp_16_reg_741_pp0_iter3_reg[2 : 1] <= tmp_16_reg_741_pp0_iter2_reg[2 : 1];
tmp_16_reg_741_pp0_iter3_reg[5 : 4] <= tmp_16_reg_741_pp0_iter2_reg[5 : 4];
        tmp_16_reg_741_pp0_iter4_reg[2 : 1] <= tmp_16_reg_741_pp0_iter3_reg[2 : 1];
tmp_16_reg_741_pp0_iter4_reg[5 : 4] <= tmp_16_reg_741_pp0_iter3_reg[5 : 4];
        tmp_16_reg_741_pp0_iter5_reg[2 : 1] <= tmp_16_reg_741_pp0_iter4_reg[2 : 1];
tmp_16_reg_741_pp0_iter5_reg[5 : 4] <= tmp_16_reg_741_pp0_iter4_reg[5 : 4];
        tmp_17_reg_751_pp0_iter2_reg <= tmp_17_reg_751_pp0_iter1_reg;
        tmp_17_reg_751_pp0_iter3_reg <= tmp_17_reg_751_pp0_iter2_reg;
        tmp_17_reg_751_pp0_iter4_reg <= tmp_17_reg_751_pp0_iter3_reg;
        tmp_17_reg_751_pp0_iter5_reg <= tmp_17_reg_751_pp0_iter4_reg;
        tmp_17_reg_751_pp0_iter6_reg <= tmp_17_reg_751_pp0_iter5_reg;
        tmp_18_reg_756_pp0_iter2_reg <= tmp_18_reg_756_pp0_iter1_reg;
        tmp_18_reg_756_pp0_iter3_reg <= tmp_18_reg_756_pp0_iter2_reg;
        tmp_18_reg_756_pp0_iter4_reg <= tmp_18_reg_756_pp0_iter3_reg;
        tmp_18_reg_756_pp0_iter5_reg <= tmp_18_reg_756_pp0_iter4_reg;
        tmp_18_reg_756_pp0_iter6_reg <= tmp_18_reg_756_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln60_fu_209_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln65_reg_721 <= add_ln65_fu_302_p2;
        or_ln65_reg_731[2 : 1] <= or_ln65_fu_313_p2[2 : 1];
        select_ln60_reg_706 <= select_ln60_fu_241_p3;
        tmp_16_reg_741[2 : 1] <= tmp_16_fu_332_p3[2 : 1];
tmp_16_reg_741[5 : 4] <= tmp_16_fu_332_p3[5 : 4];
        tmp_17_reg_751 <= {{select_ln60_fu_241_p3[2:1]}};
        tmp_18_reg_756 <= {{select_ln60_1_fu_249_p3[2:1]}};
        tmp_43_cast_reg_711[5 : 3] <= tmp_43_cast_fu_261_p3[5 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln65_reg_721_pp0_iter1_reg <= add_ln65_reg_721;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln65_1_reg_776 <= icmp_ln65_1_fu_428_p2;
        icmp_ln65_2_reg_781 <= icmp_ln65_2_fu_434_p2;
        icmp_ln65_3_reg_786 <= icmp_ln65_3_fu_440_p2;
        icmp_ln65_reg_771 <= icmp_ln65_fu_422_p2;
        or_ln65_reg_731_pp0_iter1_reg[2 : 1] <= or_ln65_reg_731[2 : 1];
        select_ln60_reg_706_pp0_iter1_reg <= select_ln60_reg_706;
        tmp_16_reg_741_pp0_iter1_reg[2 : 1] <= tmp_16_reg_741[2 : 1];
tmp_16_reg_741_pp0_iter1_reg[5 : 4] <= tmp_16_reg_741[5 : 4];
        tmp_17_reg_751_pp0_iter1_reg <= tmp_17_reg_751;
        tmp_18_reg_756_pp0_iter1_reg <= tmp_18_reg_756;
        tmp_43_cast_reg_711_pp0_iter1_reg[5 : 3] <= tmp_43_cast_reg_711[5 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_load_2_reg_791 <= conv1_output_q4;
        conv1_output_load_4_reg_797 <= conv1_output_q3;
    end
end

always @ (*) begin
    if (((icmp_ln60_fu_209_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten24_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten24_load = indvar_flatten24_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        conv1_output_ce0 = 1'b1;
    end else begin
        conv1_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        conv1_output_ce1 = 1'b1;
    end else begin
        conv1_output_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv1_output_ce2 = 1'b1;
    end else begin
        conv1_output_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_ce3 = 1'b1;
    end else begin
        conv1_output_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_ce4 = 1'b1;
    end else begin
        conv1_output_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_ce5 = 1'b1;
    end else begin
        conv1_output_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_ce6 = 1'b1;
    end else begin
        conv1_output_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        pool1_output_ce0 = 1'b1;
    end else begin
        pool1_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        pool1_output_we0 = 1'b1;
    end else begin
        pool1_output_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln60_1_fu_215_p2 = (ap_sig_allocacmp_indvar_flatten24_load + 5'd1);

assign add_ln60_fu_227_p2 = (ap_sig_allocacmp_i_load + 4'd2);

assign add_ln61_fu_365_p2 = (select_ln60_fu_241_p3 + 4'd2);

assign add_ln62_fu_291_p2 = (tmp_43_cast_fu_261_p3 + zext_ln62_fu_287_p1);

assign add_ln65_1_fu_480_p2 = (tmp_43_cast_reg_711_pp0_iter1_reg + zext_ln65_4_fu_476_p1);

assign add_ln65_fu_302_p2 = (tmp_14_fu_275_p3 + zext_ln62_fu_287_p1);

assign and_ln65_1_fu_463_p2 = (grp_fu_1544_p_dout0 & and_ln65_fu_457_p2);

assign and_ln65_2_fu_557_p2 = (or_ln65_4_fu_553_p2 & or_ln65_3_fu_549_p2);

assign and_ln65_3_fu_563_p2 = (grp_fu_1548_p_dout0 & and_ln65_2_fu_557_p2);

assign and_ln65_4_fu_647_p2 = (or_ln65_6_fu_643_p2 & or_ln65_5_fu_639_p2);

assign and_ln65_5_fu_653_p2 = (grp_fu_1552_p_dout0 & and_ln65_4_fu_647_p2);

assign and_ln65_fu_457_p2 = (or_ln65_2_fu_453_p2 & or_ln65_1_fu_449_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln65_1_fu_404_p1 = conv1_output_q6;

assign bitcast_ln65_2_fu_490_p1 = conv1_output_load_2_reg_791_pp0_iter2_reg;

assign bitcast_ln65_3_fu_507_p1 = conv1_output_q2;

assign bitcast_ln65_4_fu_580_p1 = conv1_output_load_4_reg_797_pp0_iter4_reg;

assign bitcast_ln65_5_fu_597_p1 = conv1_output_q1;

assign bitcast_ln65_fu_386_p1 = conv1_output_q5;

assign conv1_output_address0 = zext_ln65_7_fu_665_p1;

assign conv1_output_address1 = zext_ln65_6_fu_575_p1;

assign conv1_output_address2 = zext_ln65_5_fu_485_p1;

assign conv1_output_address3 = zext_ln65_3_fu_340_p1;

assign conv1_output_address4 = zext_ln65_fu_308_p1;

assign conv1_output_address5 = zext_ln65_2_fu_327_p1;

assign conv1_output_address6 = zext_ln62_1_fu_297_p1;

assign empty_61_fu_283_p1 = select_ln60_fu_241_p3[2:0];

assign grp_fu_1544_p_ce = 1'b1;

assign grp_fu_1544_p_din0 = conv1_output_q5;

assign grp_fu_1544_p_din1 = conv1_output_q6;

assign grp_fu_1544_p_opcode = 5'd2;

assign grp_fu_1548_p_ce = 1'b1;

assign grp_fu_1548_p_din0 = conv1_output_load_2_reg_791_pp0_iter2_reg;

assign grp_fu_1548_p_din1 = conv1_output_q2;

assign grp_fu_1548_p_opcode = 5'd2;

assign grp_fu_1552_p_ce = 1'b1;

assign grp_fu_1552_p_din0 = conv1_output_load_4_reg_797_pp0_iter4_reg;

assign grp_fu_1552_p_din1 = conv1_output_q1;

assign grp_fu_1552_p_opcode = 5'd2;

assign icmp_ln60_fu_209_p2 = ((ap_sig_allocacmp_indvar_flatten24_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln65_10_fu_627_p2 = ((tmp_s_fu_601_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln65_11_fu_633_p2 = ((trunc_ln65_5_fu_611_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_1_fu_428_p2 = ((trunc_ln65_fu_400_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_2_fu_434_p2 = ((tmp_4_fu_408_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln65_3_fu_440_p2 = ((trunc_ln65_1_fu_418_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_4_fu_525_p2 = ((tmp_6_fu_493_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln65_5_fu_531_p2 = ((trunc_ln65_2_fu_503_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_6_fu_537_p2 = ((tmp_7_fu_511_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln65_7_fu_543_p2 = ((trunc_ln65_3_fu_521_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_8_fu_615_p2 = ((tmp_9_fu_583_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln65_9_fu_621_p2 = ((trunc_ln65_4_fu_593_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_422_p2 = ((tmp_3_fu_390_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln60_fu_269_p2 = (trunc_ln62_fu_257_p1 | 3'd1);

assign or_ln65_1_fu_449_p2 = (icmp_ln65_reg_771 | icmp_ln65_1_reg_776);

assign or_ln65_2_fu_453_p2 = (icmp_ln65_3_reg_786 | icmp_ln65_2_reg_781);

assign or_ln65_3_fu_549_p2 = (icmp_ln65_5_reg_823 | icmp_ln65_4_reg_818);

assign or_ln65_4_fu_553_p2 = (icmp_ln65_7_reg_833 | icmp_ln65_6_reg_828);

assign or_ln65_5_fu_639_p2 = (icmp_ln65_9_reg_858 | icmp_ln65_8_reg_853);

assign or_ln65_6_fu_643_p2 = (icmp_ln65_11_reg_868 | icmp_ln65_10_reg_863);

assign or_ln65_fu_313_p2 = (empty_61_fu_283_p1 | 3'd1);

assign pool1_output_address0 = zext_ln70_fu_676_p1;

assign pool1_output_d0 = conv1_output_q0;

assign select_ln60_1_fu_249_p3 = ((tmp_fu_233_p3[0:0] == 1'b1) ? add_ln60_fu_227_p2 : ap_sig_allocacmp_i_load);

assign select_ln60_fu_241_p3 = ((tmp_fu_233_p3[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j_load);

assign select_ln65_1_fu_569_p3 = ((and_ln65_3_fu_563_p2[0:0] == 1'b1) ? add_ln65_reg_721_pp0_iter3_reg : add_ln65_1_reg_803_pp0_iter3_reg);

assign select_ln65_2_fu_659_p3 = ((and_ln65_5_fu_653_p2[0:0] == 1'b1) ? tmp_16_reg_741_pp0_iter5_reg : select_ln65_1_reg_838_pp0_iter5_reg);

assign select_ln65_fu_469_p3 = ((and_ln65_1_fu_463_p2[0:0] == 1'b1) ? zext_ln65_1_fu_446_p1 : select_ln60_reg_706_pp0_iter1_reg);

assign tmp_14_fu_275_p3 = {{or_ln60_fu_269_p2}, {3'd0}};

assign tmp_15_fu_319_p3 = {{select_ln60_1_fu_249_p3}, {or_ln65_fu_313_p2}};

assign tmp_16_fu_332_p3 = {{or_ln60_fu_269_p2}, {or_ln65_fu_313_p2}};

assign tmp_19_fu_670_p3 = {{tmp_18_reg_756_pp0_iter6_reg}, {tmp_17_reg_751_pp0_iter6_reg}};

assign tmp_3_fu_390_p4 = {{bitcast_ln65_fu_386_p1[30:23]}};

assign tmp_43_cast_fu_261_p3 = {{trunc_ln62_fu_257_p1}, {3'd0}};

assign tmp_4_fu_408_p4 = {{bitcast_ln65_1_fu_404_p1[30:23]}};

assign tmp_6_fu_493_p4 = {{bitcast_ln65_2_fu_490_p1[30:23]}};

assign tmp_7_fu_511_p4 = {{bitcast_ln65_3_fu_507_p1[30:23]}};

assign tmp_9_fu_583_p4 = {{bitcast_ln65_4_fu_580_p1[30:23]}};

assign tmp_fu_233_p3 = ap_sig_allocacmp_j_load[32'd3];

assign tmp_s_fu_601_p4 = {{bitcast_ln65_5_fu_597_p1[30:23]}};

assign trunc_ln62_fu_257_p1 = select_ln60_1_fu_249_p3[2:0];

assign trunc_ln65_1_fu_418_p1 = bitcast_ln65_1_fu_404_p1[22:0];

assign trunc_ln65_2_fu_503_p1 = bitcast_ln65_2_fu_490_p1[22:0];

assign trunc_ln65_3_fu_521_p1 = bitcast_ln65_3_fu_507_p1[22:0];

assign trunc_ln65_4_fu_593_p1 = bitcast_ln65_4_fu_580_p1[22:0];

assign trunc_ln65_5_fu_611_p1 = bitcast_ln65_5_fu_597_p1[22:0];

assign trunc_ln65_fu_400_p1 = bitcast_ln65_fu_386_p1[22:0];

assign zext_ln62_1_fu_297_p1 = add_ln62_fu_291_p2;

assign zext_ln62_fu_287_p1 = select_ln60_fu_241_p3;

assign zext_ln65_1_fu_446_p1 = or_ln65_reg_731_pp0_iter1_reg;

assign zext_ln65_2_fu_327_p1 = tmp_15_fu_319_p3;

assign zext_ln65_3_fu_340_p1 = tmp_16_fu_332_p3;

assign zext_ln65_4_fu_476_p1 = select_ln65_fu_469_p3;

assign zext_ln65_5_fu_485_p1 = add_ln65_1_fu_480_p2;

assign zext_ln65_6_fu_575_p1 = select_ln65_1_fu_569_p3;

assign zext_ln65_7_fu_665_p1 = select_ln65_2_fu_659_p3;

assign zext_ln65_fu_308_p1 = add_ln65_fu_302_p2;

assign zext_ln70_fu_676_p1 = tmp_19_fu_670_p3;

always @ (posedge ap_clk) begin
    tmp_43_cast_reg_711[2:0] <= 3'b000;
    tmp_43_cast_reg_711_pp0_iter1_reg[2:0] <= 3'b000;
    or_ln65_reg_731[0] <= 1'b1;
    or_ln65_reg_731_pp0_iter1_reg[0] <= 1'b1;
    tmp_16_reg_741[0] <= 1'b1;
    tmp_16_reg_741[3] <= 1'b1;
    tmp_16_reg_741_pp0_iter1_reg[0] <= 1'b1;
    tmp_16_reg_741_pp0_iter1_reg[3] <= 1'b1;
    tmp_16_reg_741_pp0_iter2_reg[0] <= 1'b1;
    tmp_16_reg_741_pp0_iter2_reg[3] <= 1'b1;
    tmp_16_reg_741_pp0_iter3_reg[0] <= 1'b1;
    tmp_16_reg_741_pp0_iter3_reg[3] <= 1'b1;
    tmp_16_reg_741_pp0_iter4_reg[0] <= 1'b1;
    tmp_16_reg_741_pp0_iter4_reg[3] <= 1'b1;
    tmp_16_reg_741_pp0_iter5_reg[0] <= 1'b1;
    tmp_16_reg_741_pp0_iter5_reg[3] <= 1'b1;
end

endmodule //DNN_DNN_Pipeline_VITIS_LOOP_60_1_VITIS_LOOP_61_2
